### ISSUE TITLE
Abrir segundo lote de ingressos para palestras

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#101]
Na quarta.

**Comment by map0logo** [comment]
Hi! the tutorial " I see 42 everywhere" doesn't have a description in the
page http://conf.scipyla.org/scipyla2016/participate/tutorials

In description appear "Fernando Masanori" as speaker of "Introduction to
MPI on python using mpi4py" original stated for "Jeudy Blanco".

I can give an Introductory Jupyter tutorial if you think could be useful.

Regards

F. Palm

2016-04-22 13:20 GMT-04:30 Raniere Silva notifications@github.com:

> Na quarta.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/scipy-latinamerica/scipyla2016/issues/101

## 

---

fpalm@mapologo.org.ve
francisco.palm@gmail.com

cel: +58 +424 7228252
tel: +58 +274 6352001

---

Debemos ser libres, no para hacer lo que nos plazca, sino libres para
comprender muy profundamente nuestros propios instintos e impulsos. K

**Comment by rgaiacs** [comment]
@xmnlab Você consegue corrigir isso?
