### ISSUE TITLE
Publicar palestras selecionadas no site

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#102]
Precisamos das palestras.

**Comment by melissawm** [comment]
Já fechou o período de revisão? Ou é até meia noite?

Em sex, 22 de abr de 2016 às 14:52, Raniere Silva notifications@github.com
escreveu:

**Comment by melissawm** [comment]
É normal que no site não tenha nenhuma palestra marcada como revisada? Eu
tentei revisar e meu voto não aparece lá...

Em sex, 22 de abr de 2016 às 22:41, Melissa Mendonça melissawm@gmail.com
escreveu:

**Comment by rgaiacs** [comment]
> É normal que no site não tenha nenhuma palestra marcada como revisada? Eu tentei revisar e meu voto não aparece lá...

Eu cheguei a testar essa parte do site. :-(

**Comment by rgaiacs** [comment]
Palestras publicadas.
