### ISSUE TITLE
Arte final para os crachás

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#104]

**Comment by rgaiacs** [comment]
@taliaga 
1. Você poderia adicionar o SVG de https://github.com/scipy-latinamerica/scipyla2016/blob/master/graphics_materials/badge/badge3.png?
2. https://github.com/scipy-latinamerica/scipyla2016/blob/master/graphics_materials/badge/generate.py gera cópias de https://github.com/scipy-latinamerica/scipyla2016/blob/master/graphics_materials/badge/badge.svg com os nomes dos participantes.
3. Na hora de imprimir, precisamos imprimir um lado com

![frente](https://cloud.githubusercontent.com/assets/1506457/14755892/5d2ba4fa-08dd-11e6-8514-d207205201e4.png)

e o outro lado com

![fundo](https://cloud.githubusercontent.com/assets/1506457/14755906/729d39b6-08dd-11e6-9ce5-60d2cd47ad2f.png)

depois dobramos ao meio.

**Comment by rgaiacs** [comment]
@taliaga Vai mandar o SVG.

@xmnlab Vai me ajudar com o texto.

**Comment by taliaga** [comment]
@rgaiacs Confirmando, tamanho A6 mesmo, frente e verso, certo? Me avisa aqui quando tiver definido o conteudo do verso

**Comment by rgaiacs** [comment]
@taliaga Você pode imprimir 2 crachás em casa A4. A gráfica precisa separá-los e dobrar o crachá. O tamanho final é A6.

**Comment by taliaga** [comment]
O suporte que vc comprou é pra um A6 vertical ou horizontal?

**Comment by rgaiacs** [comment]
Vertical.

**Comment by rgaiacs** [comment]
@taliaga O texto que vai dentro do crachá está em https://github.com/scipy-latinamerica/scipyla2016/blob/master/graphics_materials/badge/badge.tex.

@xmnlab Você poderia verificar o texto?

**Comment by xmnlab** [comment]
revisado e já está no repositório.

**Comment by xmnlab** [comment]
@taliaga falta alguma coisa pra finalizar a arte final deste item?

**Comment by taliaga** [comment]
@rgaiacs tem o .csv final de todos os inscritos?

**Comment by rgaiacs** [comment]
OK.
