### ISSUE TITLE
Finalização do relatório do pre-evento

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#109]
@xmnlab Você pode revisar o texto mais uma vez?

@taliaga Temos uma versão final da arte? Identidade visual para usar na capa?

@braunmagrin Você poderia adicionar o feedback das pessoas?

**Comment by xmnlab** [comment]
faço isso amanhã cedo :)

**Comment by xmnlab** [comment]
@rgaiacs não achei o link ... poderias me mandar o link do material?

**Comment by rgaiacs** [comment]
@xmnlab https://github.com/scipy-latinamerica/scipyla2016/tree/master/graphics_materials/report_demo

**Comment by rgaiacs** [comment]
@xmnlab Prometeu fazer isso amanhã.

**Comment by rgaiacs** [comment]
https://github.com/scipy-latinamerica/scipyla2016/releases/download/report-demo-1.0.0/report.pdf
