### ISSUE TITLE
Organize a Tour

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#11]

**Comment by xmnlab** [comment]
@ericnardi poderias dar uma mão nessa atividade?

o texto em português já está pronto:
https://github.com/scipy-latinamerica/scipyla2016/blob/master/city_tourism/city_tourism_pt.md

@leportella você já tem o texto em inglês?

**Comment by ericnardi** [comment]
Faço isso sim.

Onde vai ficar essa página? Dentro de _venue_?

**Comment by xmnlab** [comment]
@rgaiacs o que vc sugere? Pensei em criar uma pagina em localizaçao chamada guia de viagem (ou algo do tipo)

**Comment by xmnlab** [comment]
Obrigado @ericnardi :)

**Comment by xmnlab** [comment]
Errata: não é o submenu guia de viagem. Seria turismo na cidade.

**Comment by leportella** [comment]
Eu já dei o pull pro texto em inglês tb! Ta pronto

**Comment by xmnlab** [comment]
Onde está a versão em inglês?

Esse arquivo está vazio:

https://github.com/scipy-latinamerica/scipyla2016/blob/master/city_tourism/city_tourism_en.md

**Comment by xmnlab** [comment]
Texto em ingles ja no repositorio. Obrigado @leportella :)

**Comment by rgaiacs** [comment]
@xmnlab ficou de copiar a informação existente para o site nesse final de semana.

**Comment by rgaiacs** [comment]
Fechando por tempo.

**Comment by rgaiacs** [comment]
@xmnlab vai colocar a informação no site hoje e @rgaiacs vai adicionar o menu amanhã de manhã. Se isso não acontecer fecharemos esse issue mesmo não tendo realizado à tarefa.

**Comment by xmnlab** [comment]
@rgaiacs, acho que vc já tinha feito isso faz 24 dias:

https://github.com/scipy-latinamerica/website-scipyla2016/blob/master/scipyla2016/templates/venue/city.html

ou me equivoco?

**Comment by rgaiacs** [comment]
@xmnlab Adicionado o menu. Você poderia verificar?
