### ISSUE TITLE
Arte final para poster

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#110]
90 cm x 180 cm Sponsor Banner

**Comment by xmnlab** [comment]
Precisamos tomar cuidado para não perder o prazo com o envio do pedido de compra do banner, geralmente no minimo são 5 dias.

precisamos de 3 orçamentos para fazer via fapeu.

**Comment by xmnlab** [comment]
senão é via reembolso ... ai preciso conversar com a FAPEU para ver se não vai ter problema fazer via reembolso. Como é compra antecipada (temos que pagar antes de ter o produto e estamos com o prazo muito em cima) .. talvez vai ser via reembolso.

**Comment by rgaiacs** [comment]
> Precisamos tomar cuidado para não perder o prazo com o envio do pedido de compra do banner, geralmente no minimo são 5 dias.

Eu sei. Por isso quero finalizar isso essa semana.

> precisamos de 3 orçamentos para fazer via fapeu.

Isso é com você! Quem mandou fazer via FAPEU? :-P

**Comment by rgaiacs** [comment]
![orc](https://cloud.githubusercontent.com/assets/1506457/14797523/174ccfe0-0b2b-11e6-94e4-a0cad83eeee8.jpg)

**Comment by xmnlab** [comment]
ótimo :)

obrigado @rgaiacs :)

**Comment by rgaiacs** [comment]
@taliaga Vai ajudar com isso.

**Comment by taliaga** [comment]
3 banners

**Comment by taliaga** [comment]
@rgaiacs vou precisar do logo da numfocus em boa qualidade. O que achei na internet nao é bom o suficiente pro banner (approx 300x100px). Voce consegue pedir pra eles e me encaminhar? Pode ser formato pdf, illustrator, photoshop, corel ou svg.

**Comment by rgaiacs** [comment]
Lhe mando isso no final do dia. :-(

**Comment by taliaga** [comment]
@rgaiacs algum update do logo?

**Comment by xmnlab** [comment]
@taliaga se não vier outro logo vamos usar essa mesmo.

**Comment by xmnlab** [comment]
@taliaga falta alguma coisa pra finalizar a arte final deste item?

**Comment by taliaga** [comment]
Noup, this is ready!

**Comment by rgaiacs** [comment]
OK
