### ISSUE TITLE
Arte final do programa

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#111]
- Advertisement in program

**Comment by rgaiacs** [comment]
@taliaga Você poderia enviar o SVG?

**Comment by taliaga** [comment]
@rgaiacs vou ver se é SVG mesmo que consigo. Mas acho mais facil fazer o contrario e começar pelo conteúdo mesmo.

**Comment by rgaiacs** [comment]
@taliaga A @melissawm já trabalho no programa. Precisamos apenas da arte para a capa. Para que ela seja uniforme.

**Comment by xmnlab** [comment]
Falta definir os conteúdos.

sobre a programação o que entrará?

SWC?
rgaiacs.github.io/2016-05-16-scipyla/

Tutorial?
http://conf.scipyla.org/scipyla2016/participate/tutorials/

Apresentação?
http://conf.scipyla.org/scipyla2016/participate/presentations/

Track teen?
com a inclusão do tutorial da Larissa ficamos sem a programação.

**Comment by rgaiacs** [comment]
@xmnlab Já arrumei 90% do programa. Falta apenas direções de como chegar nas salas. Você consegue fazer isso?

**Comment by xmnlab** [comment]
eu só fui uma vez no EFI :(
Na BU é facil .. mas no EFI não sei :(
podemos mandar isso em modo digital depois? :)

2016-04-28 14:49 GMT-03:00 Raniere Silva notifications@github.com:

**Comment by xmnlab** [comment]
amanhã depois do aula/almoço eu vou nesses lugares e já faço anotações de
como chegar lá.

**Comment by taliaga** [comment]
@rgaiacs Confirmando o tamanho, o programa será tipo livreto A5 frente e verso, blz?

**Comment by rgaiacs** [comment]
@taliaga Vou responder em https://github.com/scipy-latinamerica/scipyla2016/issues/119 para manter a informação fácil de encontrar.

**Comment by rgaiacs** [comment]
@taliaga O programa deve ser impresso em A4 (2 páginas por folha). A gráfica precisa dobrar e grampear de forma que no final fique A5. A folha da capa pode ser mais densa.

**Comment by rgaiacs** [comment]
OK
