### ISSUE TITLE
Revisar amigos

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#112]
http://conf.scipyla.org/scipyla2016/friends/

**Comment by xmnlab** [comment]
precisamos colocar o logo da python brasil.

@sergiomario poderias passar-nos a imagem o link ao qual será linkada a imagem?

**Comment by sergiomario** [comment]
Segue @xmnlab :)
Link: http://2016.pythonbrasil.org.br/
Imagem: https://www.facebook.com/pythonbrasil/ (serve tanto a principal como a de capa)

**Comment by rgaiacs** [comment]
@sergiomario Faço hoje a noite.

@braunmagrin Cadê o logo da empresa onde você trabalha?

**Comment by rgaiacs** [comment]
@xmnlab vai ligar para o @braunmagrin pedindo logo.

**Comment by taliaga** [comment]
TODO: Adicionar ESSS

**Comment by xmnlab** [comment]
@taliaga consegues o logo e o endereço do link para a gente colocar no site?

**Comment by taliaga** [comment]
![esss_2_pos_rgb](https://cloud.githubusercontent.com/assets/4542117/14928055/f5326d9e-0e2b-11e6-89c3-3d0b48bcc4bd.jpg)
http://www.esss.com.br/ 
(o comment coloquei como lembrete, vou ver se coloco hoje mesmo)
update: different color

**Comment by rgaiacs** [comment]
Adicionados: http://conf.scipyla.org/scipyla2016/friends/

@braunmagrin Me manda o logo da Bravi em PNG. Me mandaram em Adobe. :-(
