### ISSUE TITLE
Airbnb

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#113]
- https://www.airbnb.co.uk/rooms/4121120?checkin=15-05-2016&checkout=21-05-2016&guests=5&s=fN7guy0H
- https://www.airbnb.co.uk/rooms/2007434?checkin=15-05-2016&checkout=21-05-2016&guests=4&s=jM8hNQCA
- https://www.airbnb.co.uk/rooms/4752229?checkin=15-05-2016&checkout=21-05-2016&guests=4&s=PULgPFQf
- https://www.airbnb.co.uk/rooms/9757671?checkin=15-05-2016&checkout=21-05-2016&guests=4&s=c9dr3yid

**Comment by xmnlab** [comment]
Primeira opção enviada para o Fetter.

**Comment by rgaiacs** [comment]
Problemas devido à planilha orçamentária. :-(

**Comment by rgaiacs** [comment]
Não vamos utilizar.
