### ISSUE TITLE
Request wifi access (eduroam) to UFSC

### ISSUE THREAD

**Issue by melissawm** [scipy-latinamerica/scipyla2016#114]

**Comment by xmnlab** [comment]
:D obrigado Melissa .. eu tava com isso pendente faz tempo :(

já sabe como fazer isso?

me falaram para fazer via setic .. mas não achei direito a opção na solicitação e acabei deixando pra depois isso ..

**Comment by melissawm** [comment]
Sim, pode deixar que sei como fazer.

Em dom, 24 de abr de 2016 às 23:39, Ivan notifications@github.com
escreveu:

**Comment by rgaiacs** [comment]
@melissawm Você precisa olhar isso para todas as três salas mais auditório.

**Comment by xmnlab** [comment]
@melissawm só uma dúvida, na rede eduroam como fazemos para liberar para as pessoas de fora? precisamos passar uma lista dos participantes com o número de documento deles?

**Comment by melissawm** [comment]
O setic cria uma rede pro nosso evento.

Em ter, 26 de abr de 2016 14:02, Ivan notifications@github.com escreveu:

**Comment by rgaiacs** [comment]
O SETIC pode fornecer as credenciais essa semana? Para incluirmos essa informação no programa?

**Comment by melissawm** [comment]
Vou ver hoje à tarde. Quando vcs pretendem mandar imprimir o programa?

Em qua, 27 de abr de 2016 04:41, Raniere Silva notifications@github.com
escreveu:

**Comment by rgaiacs** [comment]
> Vou ver hoje à tarde. Quando vcs pretendem mandar imprimir o programa?

Sexta-feira.

Eles precisam de duas semanas.

**Comment by melissawm** [comment]
Qual é o nosso número estimado de participantes? (total,
palestras+tutoriais)

Em qua, 27 de abr de 2016 às 12:57, Raniere Silva notifications@github.com
escreveu:

**Comment by xmnlab** [comment]
um minuto vou ver aqui .. quanto foi no projeto da UFSC

2016-04-27 14:31 GMT-03:00 melissawm notifications@github.com:

**Comment by xmnlab** [comment]
no projeto da ufsc está como 250 pessoas atingidas pelo evento.

no auditorio temos 180 pessoas .. e não sei quantas crianças participarão
do track teen.

poderias colocar 250?

Grande abraço,
Ivan

**Comment by melissawm** [comment]
Rede cadastrada.

Temos um email, scipy.2016@ufsc.br e acesso a rede de 16 a 20 de maio.

login scipy
senha SciPyla2016

A rede acredito que é a a eduroam. Posso checar mais tarde.

Abs

Melissa

Em qua, 27 de abr de 2016 às 14:49, Ivan notifications@github.com
escreveu:

**Comment by xmnlab** [comment]
Muito obrigado Melissa :)

**Comment by rgaiacs** [comment]
Obrigado.
