### ISSUE TITLE
Cavaletes para exposição de posteres

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#117]
**Biombo - cavalete para posteres (4)**:
Confirmado. Retirada no térreo do Centro de Eventos, ao lado da Livros e Livros.

**Suporte para banners (3)**:
A @juliamachado emprestará 2. Ainda falta conseguir um.

**Comment by xmnlab** [comment]
Email enviado ao secult.

@melissawm , precisamos de 4 cavaletes?

**Comment by melissawm** [comment]
São 4 pôsteres, mas se não me engano cada cavalete suporta até 4 pôsteres.
Podemos pedir 2 e colocar 2 pôsteres em cada cavalete... Isso tem que ser
visto com eles, conferir o modelo e tamanho do cavalete.

Em seg, 25 de abr de 2016 às 10:46, Ivan notifications@github.com
escreveu:

**Comment by xmnlab** [comment]
Ok :) Assim que eles derem um retorno eu já verifico isso com eles :)

**Comment by xmnlab** [comment]
Tem que ser visto também suporte para os 3 banners do evento.

**Comment by xmnlab** [comment]
O biombo (cavalete) está sendo analisada a disponibilidade pela SECULT.

O tripé não tem na UFSC, vamos ver se conseguimos via pregão da ufsc .. senão temos que alugar os 3 tripés.

**Comment by xmnlab** [comment]
@xmnlab vai ligar amanhã para verificar a disponibilidade do biombo

**Comment by xmnlab** [comment]
Biombo reservado!

**Comment by taliaga** [comment]
Vale a pena lembrar que os 3 banners serao de 80 \* 180 cm

**Comment by xmnlab** [comment]
@taliaga vc viu se tem um suporte para banner ai?

**Comment by rgaiacs** [comment]
Já estão reservados.
