### ISSUE TITLE
Cancelamento das salas que não serão usadas

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#119]
Verificar quais salas não serão usadas no evento e cancelar reserva.

As salas que estão reservadas são:
- auditório da mecânica;
- mini-auditório CFH;
- auditório CFH;

TODO: ver dias reservados

**Comment by rgaiacs** [comment]
@xmnlab Você pode fazer isso na segunda-feira?

**Comment by xmnlab** [comment]
faço segunda feira!

**Comment by taliaga** [comment]
Amanhã cancelo o auditorio da mecânica então!

**Comment by xmnlab** [comment]
Obrigado @taliaga!

Eu estou esperando um retorno da julia para poder cancelar as salas do CFH.

**Comment by taliaga** [comment]
Pronto, reserva da Mecânica cancelada.

**Comment by xmnlab** [comment]
@taliaga obrigado!

@melissawm já tens a definição da atividade de diversidade?
consegue me mandar amanhã essa informação para eu poder cancelar isso amanhã no fim do dia?

**Comment by rgaiacs** [comment]
Canceladas.
