### ISSUE TITLE
Call for Papers

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#12]

**Comment by rgaiacs** [comment]
@melissawm Do you have some time this week to review https://github.com/scipy-latinamerica/website-scipyla2016/blob/master/scipyla2016/templates/participate/presentations.html so that we publish it? What do you think about go with the same dates of the call for tutorials, https://github.com/scipy-latinamerica/website-scipyla2016/blob/master/scipyla2016/templates/participate/tutorials.html#L148?

**Comment by melissawm** [comment]
Done. I just need, if possible, some guidelines on what are the conditions
for acceptance for the tutorials and the presentations. Is there a document
about this from past conferences?

Em dom, 31 de jan de 2016 às 19:33, Raniere Silva notifications@github.com
escreveu:

**Comment by xmnlab** [comment]
> Done. I just need, if possible, some guidelines on what are the conditions
> for acceptance for the tutorials and the presentations. Is there a
> document
> about this from past conferences?

The only information we have into the repository is that:

https://github.com/scipy-latinamerica/scipyla2016/blob/master/organization/project.md#critérios-para-a-seleção-de-trabalhos

Is it enough?

**Comment by melissawm** [comment]
For the presentations, yes. For the tutorials, I guess we should find some
balance between the number of beginner and advanced tutorials, is that
right? I don't think we have defined how many tutorials should we have, or
how many hours should each one have. We also need to define if we will
require each participant to bring their own device for the tutorials. I
propose a guide for the tutorials proposals, to be added to the website,

# like this:

Your proposal for a tutorial should contain the following information:
- Title, abstract, keywords
- Brief outline with an estimate for how many hours the tutorial should take
- What prior knowledge is expected from participants (e.g. experience with
  SciPy, Matplotlib, pandas, etc)
- Will there be any material provided to participants? (slides, video,
  documentation etc)
  =================================================

Please contribute your opinions!

Cheers

Melissa

Em sex, 5 de fev de 2016 às 10:49, Ivan notifications@github.com escreveu:

**Comment by map0logo** [comment]
Do you think that could be helpful an Spanish version of Scipy2016 website?

If so, I think I could help with the translation. Also translating to
spanish the call for papers and workshops.

Regards

F. Palm

**Comment by melissawm** [comment]
If someone is willing to do the translation I think it makes sense, it is a
latin american conference after all :)
Em 05/02/2016 5:48 PM, "Francisco Palm" notifications@github.com escreveu:

**Comment by xmnlab** [comment]
> Do you think that could be helpful an Spanish version of Scipy2016
> website?
> 
> If so, I think I could help with the translation. Also translating to
> spanish the call for papers and workshops.
> 
> Thank you Francisco. :) could you talk to @taliagas about that? He told
> that he will help about spanish translation. :)

**Comment by xmnlab** [comment]
1 de marzo: fecha inicial para el envío de presentaciones, tutoriales y carteles (pósters) 

Como estamos com este tema? estão precisando de algo?

**Comment by rgaiacs** [comment]
@xmnlab Alguém precisa testar a submissao de tutoriais e palestras. Não vou conseguir fazer isso antes de 1º de março.

@leportella Você consegue fazer isso antes de 1º de março?

**Comment by melissawm** [comment]
- No formulário de inscrição em português (http://conf.scipyla.org/scipyla2016/account/signup/), aparece "Palavra-passe" onde deveria aparecer "Senha".
- Tentei submeter um poster aqui http://conf.scipyla.org/scipyla2016/proposals/submit/ e obtive "Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log."
- Consegui submeter um sprint, um tutorial
- Tentei submeter um talk (que aliás acho que deveria se chamar "palestra" em português) e tive o mesmo problema que com o poster.
