### ISSUE TITLE
Compra de materiais para auxilio durante o evento

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#120]
| Produto | Unidades | Compra Realizada |
| :-- | :-: | :-: |
| Pincel atômico | 3 | - |
| Post-it grande vermelho ou amarelo | 1 (com 100) | - |
| Post-it grande verde | 1 (com 100) | - |
| Post-it grande azul | 1 (com 100) | - |

**Comment by rgaiacs** [comment]
@xmnlab ainda vai comprar.
