### ISSUE TITLE
Adicionar palestra da Melissa no programa

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#122]

**Comment by melissawm** [comment]
Como o call for tutorials já tá fechado, adiciono minha descrição aqui e no programa em seguida.

Automatizando a criação de PDF's com LaTeX + Python

LaTeX é um sistema de composição tipográfica de alta qualidade, muito usado para a geração de documentos científicos (artigos, papers, teses, etc), principalmente nas ciências exatas. Entre as vantagens do LaTeX estão a geração automática de numeração de seções/capítulos/equações, o gerenciamento de texto (separação de sílabas, seleção automática de idioma) e o gerenciamento de referências bibliográficas, incluindo citações e formatação (utilizando bibLaTeX).

Neste tutorial, vamos estudar uma introdução rápida ao LaTeX e como utilizar Python+LaTeX pra automatizar a geração de documentos PDF. Exemplos incluem:
- Geração automática de certificados, com nomes extraídos de um banco de dados sqlite
- Geração automática de gráficos a partir de dados numéricos usando TiKZ
- Geração de tabelas com dados obtidos do código
- Utilização de pandas+scikit-learn pra geração de métricas sobre dados obtidos pelo código e posterior geração de relatório com gráficos, tabelas, etc
- Visualização de dados em documentos PDF (para impressão)

Utilizaremos bibliotecas básicas do python e também um pouco de pandas/scipy para alguns exemplos.

**Comment by melissawm** [comment]
Opa, uma dúvida: esse meu tutorial entraria então no lugar deste?
5/17/2016   9:00-12:00  Auditório Elke Hering  DSL on the top of Python Object Model   Juan Cabral     Introductory

**Comment by xmnlab** [comment]
Oi Melissa, estamos com o mini-auditorio sobrando.
Além disso, vou ver com a @juliamachado de abrir um horario de debates para
temas de diversidade no mesmo auditorio. Assim a gente cobriria melhor esse
tema no evento.

ainda não marquei horario com ela .. to vendo agora com ela .. sugeri hoje,
para segunda feira já tocar ficha ... assim que eu marcar com a
@juliamachado te aviso.

**Comment by xmnlab** [comment]
@melissawm, vai ser hoje por volta das 18h. Qq coisa dá um grito ;)

**Comment by rgaiacs** [comment]
> Opa, uma dúvida: esse meu tutorial entraria então no lugar deste?
> 5/17/2016 9:00-12:00 Auditório Elke Hering DSL on the top of Python Object Model Juan Cabral Introductory

Não. O seu tutorial é na Sala de projeção Harry Laus no dia 5/17/2016 as14:00-17:00.

**Comment by rgaiacs** [comment]
Adicionado. http://conf.scipyla.org/scipyla2016/participate/tutorials/
