### ISSUE TITLE
Arte final para os certificados

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#125]
@taliaga Você também pode ajudar nisso?

Exemplo: https://github.com/scipy-latinamerica/scipyla2016/tree/master/graphics_materials/certificates

**Comment by taliaga** [comment]
Sure!

**Comment by melissawm** [comment]
Eu tenho um script python que lê dados de um banco sqlite e gera os
certificados automaticamente a partir de um template, em LaTeX. Se quiser
tá no meu github mas posso alterar o template pra ficar como vcs quiserem.

Abs

Em sex, 29 de abr de 2016 às 20:35, Tomas notifications@github.com
escreveu:

**Comment by rgaiacs** [comment]
@taliaga Esqueci de avisar que só vamos precisar disso depois do evento. :-)
