### ISSUE TITLE
Adicionar mapas no programa

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#132]
@xmnlab ou @taliaga vocês conseguem pegar os mapas de http://conf.scipyla.org/scipyla2016/venue/ mostrando as salas e colocar no programa?

**Comment by xmnlab** [comment]
@rgaiacs como os participantes de qq forma iram ao evento para ter que pegar o programa e, nem todo mundo vai ganhar o programa. acho que nem vale a pena fazer isso.

talvez além do twitter que vc mandou, mandar um email para todos os inscritos com o link da página onde está a localização da página. Acho que isso sería já suficiente.
