### ISSUE TITLE
Airport transfer

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#134]
If you are going to arrive in Florianópolis by plane and want to share a taxi please mention your flight here.

**Comment by ocefpaf** [comment]
Eu chego dia 15

```
IDA 15   MAI    GOL  5441   
Sao Paulo - Congonhas (CGH)
Florianópolis (FLN)
13:10   14:20
```

**Comment by rgaiacs** [comment]
Ida: 14 de Maio G3 6751
Saída: GRU - 10:10
Chegada: FLN - 11:10

Retorno: 22 de Maio G3 6747
Saída: FLN - 18:25
Chegada: GRU - 19:25
