### ISSUE TITLE
Finalizar relatório

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#137]
Rascunho em https://github.com/scipy-latinamerica/scipyla2016/blob/master/print_materials/reports/general/report.tex.

**Comment by braunmagrin** [comment]
Rola trabalharmos no Overleaf? Dai fica bem fácil colaborar ao mesmo tempo.
Posso passar pra lá se gostarem da ideia.

**Comment by rgaiacs** [comment]
> Rola trabalharmos no Overleaf?

Adiciona nos comentário so que você quer adicionar que eu ou o @xmnlab fazemos a alteração nessa semana. Queremos concluir isso o mais rápido possível.

**Comment by rgaiacs** [comment]
@braunmagrin você pode ver o PDF em https://github.com/scipy-latinamerica/scipyla2016/releases/tag/report-1.0.0-alpha.

**Comment by ankanaan** [comment]
Não achei o campo de comentários, então vou mandar aqui mesmo.  Escrevi um
parágrafo sobre a jovem trilha astronômica, me avisem se escrevi demais ou
de menos, está no final da mensagem.

Abaixo catei algumas palavras trocadas, erros de digitação, etc.

Achei um S sobrando na frase abaixo no texto.

"realizados em paralelo" em vez de "realizados em paraleloS"

e aqui é auto ou aLto, eu acho que é aLto, aUto-desempenho deve ser algo de
python-psicologia :-)

"processamento de dados e auto-desempenho,"

trocar por O:   TodAs os lugares escolhidos

são AGLOMERADOS e não "conglomerados de estrelas"

Ou tira o COM ou a crase:  "relacionadas com à organização"

Sobre a trilha jovem:

Trilha jovem:

O Prof. Antônio Kanaan do Departamento de Física, CFM, UFSC, ministrou um
minicurso para 20 adolescentes de idades entre 11 e 15 anos.  Todos os
alunos são da Escola Básica Prof.ª Herondina Medeiros Zeferino.  O curso
foi uma rápida introdução aos conceitos básicos de computação através da
criação de um algoritmo para calcular os primeiros números primos.  Em
seguida introduzimos o conceito de objetos e com isso entramos no Chimera,
o nosso programa de controle de observatórios robóticos.  Os alunos
visitaram o observatório e movemos o telescópio e tiramos algumas imagens
usando o que desenvolvemos na aula no laboratório de informática do
Departamento de Física.
