### ISSUE TITLE
Editar e publicar videos palestras

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#139]
### 18/05/2016
- [ ] Welcome   Ivan Ogasawara
- [ ] Lightning talks   (18/05/2016)
- [ ] Sinestesia científica - Explorando dados através da música, com DataSounds - Arnaldo Russo
- [ ] The numba library - Edison Gustavo Muenz
- [ ] Software Carpentry - Raniere Silva
- [ ] External Commands - Juan Cabral
- [ ] import community - Fernando Masanori
### 19/05/2016
- [ ] Conda-forge and the future of the Scientific Python packaging - Filipe Fernandes
- [ ] Geração da Fármacos com Python - Mário Ségio de Queiroz
- [ ] Lightning talks (19/05/2016)
- [ ] Fighting techniques in kaggle war - Emilio Simoni
- [ ] 3DBMO: A Python Tool to Study the Power Spectrum Dimensional Dependence in Complex Physical Systems - Paulo Giovani
- [ ] A Simplificação Textual como instrumento de inclusão cognitiva - Vinicius Woloszyn
- [ ] Solving Math Programming Problems with Python - Eduardo Silva
- [ ] Round table about how to run your own event - Ivan Ogasawara, Raniere Silva
### 20/05/2016
- [ ] Round table about SciPy Latin America 2017
- [ ] Interactive Data Visualization in the Browser with Bokeh - Bryan Van de Ven
- [ ] Lightning talks (20/05/2016)
- [ ] Ecuaciones diferenciales con Python - Raul Lopez Briega
- [ ] Localiza, una biblioteca para la localización óptima de equipamientos sociales - Francisco Palm
- [ ] Learning Analytics: utilizando Data Science para melhorar a educação - Matheus Braun Magrin
- [ ] From SCADA to IoT with Python - Nahuel Defossé
- [ ] Concluding discussion - Ivan Ogasawara, Raniere Silva

**Comment by rgaiacs** [comment]
# Instruções para edição dos videos
1. Edite https://github.com/scipy-latinamerica/scipyla2016/blob/master/print_materials/video_cover/template.svg corrigindo o nome da palestra e do palestrante.

![t](https://cloud.githubusercontent.com/assets/1506457/15838067/1951fc50-2c34-11e6-884e-0804e000ebd3.png)
1. Utilize o [kdenlive](https://kdenlive.org/) ou o [openshot](http://openshot.org/) para editar o video.
   
   O vídeo deve começar a capa editada no item anterior.
   
   O resolução de saída do vídeo deve ser 720.

# Instruções para publicação do vídeo

Os vídeos devem ser publicados em ??? (@xmnlab vai dizer onde!)

**Comment by leandroqm** [comment]
@xmnlab Sign me in! :-)

**Comment by xmnlab** [comment]
@leandroqm ja te adicionei no grupo de trabalho:)

**Comment by leandroqm** [comment]
Pessoal, fica uma dica para as próximas filmagens de eventos:

O cartão foi formatado em algum filesystem que suporta somente 2GB como tamanho máximo de cada arquivo.
Isso faz com que toda vez que o arquivo sendo gravado atinge 2GB, é necessário criar outro para continuar a filmagem.
O resultado disso são falhas (gaps) nestes pontos específicos que, infelizmente, mão tem como ser corrigidos na edição.

Abraços!

**Comment by xmnlab** [comment]
valeu Leandro!! :)

grande abraço,
Ivan

**Comment by rgaiacs** [comment]
@leandroqm o cartão foi formatado no filesystem fornecido pelo fabricante. Não sei se EXT4 é suportado.

**Comment by leandroqm** [comment]
Pois é, Raniere. NTFS geralmente é suportado e vai até 16EiB, o que significa que um único arquivo pode tomar o cartão inteiro, caso necessário! :-)

Hoje à noite, por volta de 20h (GMT-3), devo subir um bocado de vídeos (de 5 a 8 vídeos, dependendo do tempo de renderização).

Abraços.

**Comment by leandroqm** [comment]
Neste momento, todos os vídeos foram editados e renderizados.
Vou deixar esta madrugada o computador ligado enviando para o Youtube, então amanhã devem estar todos no canal.

Forte abraço a todos!

**Comment by olemis** [comment]
eu preciso <translate from="es" to="pt">descargar</translate> todo isso

ok , no hablo portugués , pero tenía q comentar algo al respecto :)

On 6/23/16, Leandro Quibem Magnabosco notifications@github.com wrote:

> Neste momento, todos os vídeos foram editados e renderizados.
> Vou deixar esta madrugada o computador ligado enviando para o Youtube, então
> amanhã devem estar todos no canal.
> 
> Forte abraço a todos!
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/scipy-latinamerica/scipyla2016/issues/139#issuecomment-228245140

## 

Regards,

Olemis - @olemislc

Apache™ Bloodhound contributor
http://issues.apache.org/bloodhound
http://blood-hound.net

Brython committer
http://brython.info
http://github.com/brython-dev/brython

SciPy Latin America - Cuban Ambassador
Chairman of SciPy LA 2017

Blog ES: http://simelo-es.blogspot.com/
Blog EN: http://simelo-en.blogspot.com/

Featured article:
