### ISSUE TITLE
Hotel

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#14]

**Comment by xmnlab** [comment]
feito: http://conf.scipyla.org/scipyla2016/lodging/

**Comment by melissawm** [comment]
Pessoal, vcs discutiram descontos com o Slaviero? Para conferências na ufsc eles costumam fazer um preço mais em conta. Vale a pena perguntar...

**Comment by xmnlab** [comment]
@melissawm bom saber :) muito obrigado! vou adicionar aqui na lista de atividades :)

**Comment by rgaiacs** [comment]
From slavierohoteis.com.br

> Categoria Luxo (cama de casal ou duas camas de solteiro) – R$ 219,00
> single / R$ 249,00 double + 2,5% ISS, café da manhã incluso.
> Categoria Luxo Superior (cama de casal ou duas camas de solteiro +
> sofá cama) – R$ 249,00 single / R$ 279,00 double / R$ 309,00 triplo +
> 2,5% ISS, café da manhã incluso.
> Categoria Suíte (cama de casal + sofá cama) – R$ 269,00 single / R$
> 299,00 double / R$ 329,00 triplo + 2,5% ISS, café da manhã incluso.

@xmnlab Vai dar resposta para eles e proceder de acordo (e.g. fazer a inclusão no site).

**Comment by rgaiacs** [comment]
@xmnlab vai colocar as informações do  slavierohoteis.com.br amanhã no site.

**Comment by xmnlab** [comment]
feito
