### ISSUE TITLE
Travel Guide

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#16]

**Comment by xmnlab** [comment]
@ericnardi poderias dar uma força nessa issue?
Aqui te deixo a travel guide do ano passado como referência: https://github.com/scipy-latinamerica/scipyla2015/blob/master/travel_guide/htt_pt.md

**Comment by ericnardi** [comment]
ok, vou ver o que consigo fazer.

**Comment by xmnlab** [comment]
Obrigado @ericnardi. Acho que podemos criar um submenu, em localizaçao, chamado guia de viagem. :)

**Comment by rgaiacs** [comment]
@ericnardi O submenu é criado utilizando o sitetree. Você precisa abrir o painel administrativo, criar o submenu e exportar os submenus para `fixtures`. Esse processo está documentado no `README`. Se tiver qualquer dificuldade só comentar aqui. :-)

**Comment by ericnardi** [comment]
Tranquilo, ainda não tive tempo de olhar isso, mas acho que me viro.
Qualquer coisa aviso, obrigado!

Em qui, 25 de fev de 2016 às 17:34, Raniere Silva notifications@github.com
escreveu:

**Comment by rgaiacs** [comment]
@ericnardi Você consegui trabalhar nisso durante a próxima semana?

**Comment by xmnlab** [comment]
@gotanb poderias dar uma força nessa atividade?

**Comment by rgaiacs** [comment]
Vamos fechar e reabrir depois.
