### ISSUE TITLE
Tea and chocolate room

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#18]
We need a chocolate room, https://instagram.com/p/9zF0xPM3Wc/, because they are **awesome**.

**Comment by rgaiacs** [comment]
**Cancelado até mais próximo do evento.**

**Comment by rgaiacs** [comment]
@melissawm 
1. Podemos ter uma mesa dentro do auditório ou podemos ter uma mesa proximo?
2. Existe uma copa próxima onde podemos esquentar água? Ou alguém possui uma chaleira elétrica?

**Comment by melissawm** [comment]
Sim, podemos. Tem uma cozinha no EFI, posso perguntar se a gente poderia
usar. Em último caso, tem uma lanchonete e eu conheço o dono, podemos ver
com ele. Na verdade essa lanchonete fornece um coffee break a preço legal e
bem gostoso (já usamos). Se quiserem posso fazer um orçamento de coisa
simples (café e suco, biscoitos)

Em seg, 25 de abr de 2016 às 19:09, Raniere Silva notifications@github.com
escreveu:

**Comment by xmnlab** [comment]
eu acho válido a ideia :)

**Comment by xmnlab** [comment]
pelo menos pra ter uma ideia :)

mas pela programação do evento ... deixamos um intervalo grande de café pra
dar tempo da galera sair ir na lanchonete e ir comer.

**Comment by melissawm** [comment]
É no térreo e o auditório é no primeiro andar, então é bem tranquilo.

Em qua, 27 de abr de 2016 às 14:53, Ivan notifications@github.com
escreveu:

**Comment by rgaiacs** [comment]
Vamos fazer apenas para as palestras.
