### ISSUE TITLE
Contact international communities to support the conference

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#19]
**Please edit this comment directly instead of comment at this issue**.
- [x] Argentina - will be done by the ambassador
- [x] Bolivia - will be done by the ambassador
- Brasil
  - [x] Python Brasil 2015 (lightning talk) by @sergiomario
- Chile
  - [x] pythonchile (groups.google.com/forum/#!forum/pythonchile) by @xmnlab 
- Colombia
  - [x] pyco (groups.google.com/forum/#!forum/pyco) by @xmnlab 
  - [x] will be done by the ambassador
- Costa Rica
  - [x] PythonCostaRica (www.facebook.com/PythonCostaRica) by @xmnlab 
- [ ] Cuba
- [ ] Ecuador
- [ ] El Salvador
- Guatemala 
  - [x] will be done by the ambassador
- [ ] Haiti
- [ ] Honduras
- México
  - [x] will be done by the ambassador
  - [x] pymt (groups.google.com/forum/#!forum/pymty) by @xmnlab 
  - [x] pythoncabal (groups.google.com/forum/#!forum/pythoncabal) by @xmnlab 
  - [x] pythonmexico (mx.groups.yahoo.com/neo/groups/pythonmexico) by @xmnlab 
- Nicaragua
  - [x] pythonicaragua (www.facebook.com/pythonicaragua) by @xmnlab 
- Panamá
  - [x] Panamá´s Python Meetup Group (www.meetup.com/es/Panama-Python-Meetup/) by @xmnlab 
- [ ] Paraguay
- Perú
  - [x] python-peru (https://groups.google.com/forum/#!forum/python-peru) by @xmnlab 
- [ ] República Dominicana
- [ ] Uruguay
- Venezuela
  - [x] python-venezuela (https://groups.google.com/forum/#!forum/python-venezuela) by @xmnlab

**Comment by rgaiacs** [comment]
@xmnlab Could you add the link to the groups subscription page and add your nick as the person that contact the group?

**Comment by xmnlab** [comment]
Sure! I will do it this weekend. It will much better! Thank you :)

**Comment by rgaiacs** [comment]
@xmnlab Can we close this?

**Comment by xmnlab** [comment]
I will close this after the carnival :)

**Comment by xmnlab** [comment]
Vou finalizar essa issue até o dia 1 de março. Espero amanhã terminar o 1o anúncio e já dou divulgação junto com o anúncio.

**Comment by rgaiacs** [comment]
@xmnlab Prometeu fechar essa issue no final de semana.

**Comment by xmnlab** [comment]
feito: https://github.com/scipy-latinamerica/scipyla2016/blob/master/organization/python-commuties-contact.md
