### ISSUE TITLE
Organize the Tutorial

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#21]

**Comment by rgaiacs** [comment]
Minha sugestão é ter duas trilhas. Uma trilha para iniciante que pode ser um workshop da Software Carpentry e uma trilha para intermediários que pode focar em demos/tutoriais de ferramentas, e.g. mpi4py.

**Comment by rgaiacs** [comment]
@xmnlab Duplicate of #57?

**Comment by xmnlab** [comment]
¿@jeudy cómo estás? a partir del 1 de marzo ya estaremos aceptando las propuestas de tutoriales. ¿Estamos listos? ¿Necesitas de algo?

**Comment by rgaiacs** [comment]
Fechado porque abrimos a chamada de trabalhos.
