### ISSUE TITLE
Organize the Post-event

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#22]

**Comment by rgaiacs** [comment]
Talvez devessemos cancelar o pos evento pela proximidade com a PyCon? Talvez não tenhamos muitos desenvolvedores para liderar os sprints?

**Comment by xmnlab** [comment]
+1

Se ninguém se manifestar contra até o fim de semana .. ai eu retiro do projeto.

**Comment by rgaiacs** [comment]
We are dropping this to avoid conflict with PyCon US. (T_T)
