### ISSUE TITLE
Timetable

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#23]
Timetable definition for all tasks

**Comment by xmnlab** [comment]
Primeira versão das atividades e datas estimadas da organização do evento:
https://github.com/scipy-latinamerica/scipyla2016/blob/master/organization/agenda.md

**Comment by rgaiacs** [comment]
@xmnlab Só devemos pedir patrocínio em Janeiro. Ninguém vai olhar email na semana do natal.

**Comment by xmnlab** [comment]
ok ;)
