### ISSUE TITLE
Sponsorship packages

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#24]
Are we going to keep the same sponsorship packages from 2015?
- Diamond (US$3000)
- Gold (US$2500)
- Silver (US1250)
- Bronze (US$1000)

What will be the benefits for each package?

@xmnlab all partnerships should goes into one sponsorship package. E.g. someone will be a bronze sponsor paying their contribution of US$1000 by waiving the fee for the room.

**Comment by rgaiacs** [comment]
@xmnlab I update the text about sponsorship at https://github.com/scipy-latinamerica/website-scipyla2016. Could you comment.

**Comment by rgaiacs** [comment]
I added the banner for sponsors: https://github.com/scipy-latinamerica/scipyla2016/blob/master/banner/sponsor.svg.

**Comment by rgaiacs** [comment]
| Level | Amount | Quantity | Total |
| --- | --- | --- | --- |
| Platinum | US$3000.00 | 2 | US$6000.00 |
| Gold | US$2500.00 | 4 | US$10000.00 |
| Silver | US$1250.00 | 6 | US$7500.00 |
| Bronze | US$100.00 | ? | ? |

@xmnlab The total will be > US$2350.00.

**Comment by xmnlab** [comment]
I think 8 for bronze level is good

**Comment by rgaiacs** [comment]
@xmnlab At https://github.com/scipy-latinamerica/website-scipyla2016/commit/46b636286894b690b2cbd5dce2480606e90721c3 I change the CSS so we can generate a PDF from the website using the web browser print feature.

**Comment by xmnlab** [comment]
great! thank you! :)

**Comment by xmnlab** [comment]
can we close this issue?
