### ISSUE TITLE
Crowdfunding

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#25]
From what FAPEU said to @xmnlab and me there is no problem using crowdfunding.
# Define Platform

Most popular worldwide:
- [ ] https://www.kickstarter.com/
- [ ] https://www.indiegogo.com/

Most popular in Brazil:
- [ ] http://catarse.me/
  
  **Is based on free/open source software**: https://github.com/catarse/catarse.
- [ ] http://www.kickante.com.br/
# Define Rewards

**Need cost estimation.**
- [x] Pen
- [x] Notebook
- [x] Tshirt
- [ ] Ecobag
- [ ] Book, e.g. http://physics.codes/
- [ ] Coffee-break
- [ ] Dinner

**Comment by rgaiacs** [comment]
@xmnlab Do you know of a bar closer to the event venue that offer gourmet beer? One of the reward could be one free beer at that bar at the end of the day.

**Comment by xmnlab** [comment]
good idea ... here in floripa has a lot of local beers ... Primata sandwich bar is a good option: https://www.facebook.com/primataaorigemdosabor/photos/a.824647204269955.1073741828.821906721210670/863817553686253/?type=3&theater

**Comment by rgaiacs** [comment]
@xmnlab Maybe we could run more than one crowdfunding. For example we could run one in February for the stickers.

**Comment by leportella** [comment]
Done: 

asked 3 prices for pens, etc...
asked price for t-shirts
asked 3 prices for coffe breaks

**Comment by leportella** [comment]
**PREÇOS BS2 BRINDES (FLORIANÓPOLIS)**
http://www.b2sbrindes.com.br/

Caneca plástica cod. 1727
personalização 3 cores
Quant, 100unid. ( pedido mínimo)
Valor unit. R$ 13,90

Caneta plastica  cod. 1003
personalização 3 cores
Quant. 300unid. ( pedido mínimo)
valor unit. R$ 2,40

Boneco Hub com 4 saidas USB
personalização 3 cores
Quant, 100unid. ( pedido mínimo)
valor unit, R$ 15,80

Bottons estilo americano  com 4,5cm. diam.
personalização 3 cores
Quant, 50 unid. ( pedido mínimo)
valor unit. R$  4,50
Quant. 100 unid.
valor unit. R$  3,40

**Comment by leportella** [comment]
**PREÇOS BRINDES FLORIANÓPOLIS**
http://www.brindesflorianopolis.com.br

100         caneta teresina  R$ 1,50 à und  
50          bloco ecologico com caneta brasilia    R$ 9,90 à und

**Comment by leportella** [comment]
**SANTA CATARINA BRINDES**
http://www.santacatarinabrindes.com.br/brindes/index.jsp

100         bloco ecologica stand    R$ 9,90 à und  
100         caneca de acrilico franca       R$ 4,90 à und  
100         pen-card cartao   R$ 27,90 à und 4 Gb

**Comment by leportella** [comment]
**CAMISETAS SOMAR**

Frente: Logo da SciPyLA 2016 
Costas: Florianópolis, 2016

Cor: branco

Modelo: Camisetas, manga curta, adulto/ infantil;

Estampa: com serigrafia frente 3 cores, costas 1 cor      

Para 30 camisetas

Em malha penteada 30/1(100%algodão)(SOMAR CLASSIC-etiq.preta)unid. R$15,00

Para 100 camisetas

Em malha penteada 30/1(100%algodão)(SOMAR CLASSIC-etiq.preta)unid. R$12,50

Tamanhos camisetas temos:

Adulto (unisex): PP-P-M-G-GG (PP somente na malha somar Classic e Poliviscose)
XG + R$ 3,00
XXG + R$ 4,50  (somente na malha somar Classic e Poliviscose)
Nobre + 11,00 (somente na malha somar Classic)
Gola V + R$1,00 (somente na malha Classic)

Baby Look (feminina): M-G-GG-XG  (mesmo valor das camisetas) (Nazca Baby Look até GG)
Prazo de entrega: Até 04 dias ÚTEIS após a confirmação do pedido/arte final
Pagto: 50% depósito + 50% contra-entrega (aceitamos cartão de crédito, débito, cheque e dinheiro)
Frete: FOB Cliente retira na loja em São José
Cliente fornece a arte feita em Corel DRAW (vetorizado), com layout.
Tamanho máximo da estampa 28 cm largura x 33cm de altura;

**Comment by leportella** [comment]
**COFFE-BREAK AROMA IDIOMAS**

[leticia - 100 pessoas.pdf](https://github.com/scipy-latinamerica/scipyla2016/files/119583/leticia.-.100.pessoas.pdf)

**Comment by rgaiacs** [comment]
> só queria ter uma ideia do qto vcs acham q seria viavel ganhar em cada pacote

O objetivo principal do financiamento coletivo é conseguirmos apenas verba para os brindes.

Iremos utilizar o patrocínio para o auxílio financeiro e **não** para espaço, coffee break, swags, confraternização, ... Com o financiamento coletivo podemos oferecer adesivos, credenciais, ecobags, camisetas, ...

A divisão dos custos deve ser algo como

| Uso | Valor (%) |
| --- | --- |
| Taxa do Catarse | 13 |
| Taxa da FAPEU | 10 |
| "Seguro" ao SciPyLA | **Y** |
| Recompensas | 100 - **X** - **Y** - 10 |

O "seguro" é para cobrir flutuações nos orçamentos.

**Comment by leportella** [comment]
**COFFE-BREAK CAFÉ DAS AMÉRICAS**
[orçamento kit coffee break.pdf](https://github.com/scipy-latinamerica/scipyla2016/files/126285/orcamento.kit.coffee.break.pdf)

**Comment by xmnlab** [comment]
@rgaiacs @taliaga @leportella @braunmagrin Como ficamos com a questão do financiamento coletivo? o que falta? vamos lançar?

**Comment by leportella** [comment]
Tem que ver a questão do crachá e quais as combinações que vamos fazer. Depois disso, só lançar, ao meu ver

Temos que ver a taxa da Fapeu e etc pra saber o qto temos que "lucrar" em cada kit

**Comment by xmnlab** [comment]
Podemos fazer um hangout hoje pra definir esses itens?

**Comment by leportella** [comment]
hoje eu provavelmente nao vou poder :/

**Comment by rgaiacs** [comment]
**Fechado por falta de pessoa para cuidar do projeto.**
