### ISSUE TITLE
UFSC's logo

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#30]
Do you have UFSC's logo? Can we ask it for FAPEU?

**Comment by xmnlab** [comment]
In this page, there are some UFSC's logo options:

http://identidade.ufsc.br/arquivos/

**Comment by rgaiacs** [comment]
![screen shot 2015-12-21 at 14 58 23](https://cloud.githubusercontent.com/assets/1506457/11936205/6a88c42a-a7f3-11e5-8895-907463132581.png)
