### ISSUE TITLE
Need someone to coordinate the tutorials

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#31]
I thought in Fernando Masanori Ashikaga.

@xmnlab Could you make the invitation?

**Comment by xmnlab** [comment]
Invitation sent.

**Comment by rgaiacs** [comment]
@xmnlab do you remember someone else that could coordinate the workshops? Someone from Argentina?

**Comment by xmnlab** [comment]
We can ask to Damian. What do you think? Or maybe we can ask to Jeudy,
professor at Universidad de Costa Rica.

**Comment by rgaiacs** [comment]
> We can ask to Damian. What do you think?
> Or maybe we can ask to Jeudy, professor at Universidad de Costa Rica.

+1 for both.

**Comment by xmnlab** [comment]
Do we make the invitation to both?

**Comment by rgaiacs** [comment]
> Do we make the invitation to both?

Yes. But make sure to mention that we inviting the other to co-chair the tutorials.

**Comment by xmnlab** [comment]
done! Jeudy is the chair of the tutorials and Damián will be help us informally :)
