### ISSUE TITLE
Email @scipyla.org

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#33]
@leliel12 Do you already have one?

**Comment by rgaiacs** [comment]
This is blocking contact sponsors.

**Comment by rgaiacs** [comment]
@xmnlab what about `2016@scipyla.org`?

**Comment by xmnlab** [comment]
It sounds good :)

**Comment by xmnlab** [comment]
done .. thanks @vkmc !
