### ISSUE TITLE
Need map of venue

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#34]
@xmnlab Could you get a map of the venue? Preferable in SVG. =)

**Comment by nestornav** [comment]
I'm not designer but I'll take it.

**Comment by rgaiacs** [comment]
Dependendo do fechamento da reserva de salas.

**Comment by xmnlab** [comment]
@rgaiacs  salas reservadas, vou detalhar as reservas em um arquivo e depois deixo o link aqui.

@nestornav cuando tenga las informaciones sobre las salas en el repositorio te hago saber ;)

**Comment by nestornav** [comment]
@xmnlab excelente, voy a estar esperando.

**Comment by nestornav** [comment]
@rgaiacs @xmnlab I'll off line in May from 7th to 22 th for vacations. Do you have the venues already?

**Comment by rgaiacs** [comment]
@xmnlab ?

**Comment by xmnlab** [comment]
Hola @nestornav, ya tenemos algunas informaciones, voy a arreglar ya lo que tenemos y agregar más información y esta semana te envío lo que tenemos :) 

¿tienes tiempo para un hangout el miercoles?

**Comment by nestornav** [comment]
Hola Iván,

El Miércoles acordamos y hacemos un hangout no hay problema.

Saludos

**Comment by rgaiacs** [comment]
@xmnlab Vai fazer isso esse final de semana sem falta.

**Comment by xmnlab** [comment]
@nestornav perdón por la demora, aquí te comparto las informaciones del local: 

Universidad:
http://identidade.ufsc.br/mapa/

Sala ponencias:
http://efi.prograd.ufsc.br/files/2013/09/mapa-acesso-EFI-013.jpg

Salas tutoriales:
los tutoriales serán realizados en la Biblioteca Central (punto 17)
-> http://eneac2013.ufsc.br/files/2012/04/mapa_ufsc.gif
No he podido encontrar un mapa interno del local.

Si necesitas de alguna información, por favor hazmelo saber!

**Comment by rgaiacs** [comment]
Precisamos disso para essa semana para poder incluir no material impresso.

**Comment by xmnlab** [comment]
@nestornav te alcanza hacerlo hasta viernes por la mañana?
Así podremos incluirlo en los materiales impresos.

**Comment by nestornav** [comment]
@xmnlab @rgaiacs voy a tratar de tenerlos para la fecha que planteas.

**Comment by rgaiacs** [comment]
I will copy the open street map tomorrow.

**Comment by nestornav** [comment]
Raiere,

I'm a little bit confused about the maps. Did you check the map which I
sent you?. I don't know what kind of maps do you need.

I don't have a lot of free time to do that for the due date. So I need some
help tonight. I sent the mail with the sample this morning.

Regards

**Comment by rgaiacs** [comment]
@nestornav Thanks for your help. I will work on this tomorrow.

**Comment by xmnlab** [comment]
feito rascunho em papel. será enviado ao @rgaiacs para fazer versão digital e colocar no site.

foi colocado no site a localização no googlemaps da BU e EFI para facilitar o acesso via gps (http://conf.scipyla.org/scipyla2016/venue/).

**Comment by rgaiacs** [comment]
> será enviado ao @rgaiacs para fazer versão digital e colocar no site.

Vou fazer isso apenas quando estiver em Florianópolis.
