### ISSUE TITLE
Scavenger Hunt

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#37]
[Scavenger hunt](https://en.wikipedia.org/wiki/Scavenger_hunt), as defined in Wikipedia, "is a party game in which the organizers prepare a list defining specific items, which the participants – individuals or teams – seek to gather all items on the list – usually without purchasing them – or perform tasks or take photographs of the items, as specified."

We can organize a scavenger hunt among the participants to fill a sheet with signatures of others participants that had achieve some goals. Some examples of goals:
1. Attend all SciPyLA events so far.
2. Has a commit/patch on the source tree of NAME_OF_ONE_PROJECT.
3. Visit more than 4 Latin America countries. **Note for organization: many of the attends could easily visit Argentina, Brazil, Paraguay and Uruguay.**
4. Don't know how to ride a bicycle.
5. Is member of the board of directors of one organization.
6. Never have a sea bath.
7. Can speak more than 4 languages. **Note for organization: many of the attends could easily speak English, Portuguese and Spanish.**
8. Can program in more that 6 languages. **Note for organization: many of the attends could easily program in Bash, C, Fortran, Python, R, Julia, MATLAB/GNU Octave, Scilab, SQL, Lisp, Perl, Scala, Haskell, ...**

It will be super fun.

**Comment by xmnlab** [comment]
you're right .. it will be very nice :)

**Comment by rgaiacs** [comment]
**Fechado por falta de pessoa para cuidar.**
