### ISSUE TITLE
Visa

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#39]
> temos que coletar informações sobre visto .. pelo menos para os paises da américa latina  :-/ ... tinha esquecido disso rsrsrs mercosul eu sei q é de boa .. o restante não sei como funciona .. depois vou abrir um issue sobre isso

@xmnlab Acho que nenhum paíz da américa latina tem problemas para entrar no Brasil. Até onde eu sei, deixamos os participantes procurarem de visto e se for o caso eles entram em contato pedindo carta convite. Só precisa ter uma página com essa informação.

**Comment by leliel12** [comment]
http://www.conbrasil.org.ar/consbrasil/visas_otros01engl.asp <<< i found
this on the argentinian consulate page. All the mercosur members don't need
any kind of visa

On Mon, 28 Dec 2015 at 20:09 Raniere Silva notifications@github.com wrote:

> temos que coletar informações sobre visto .. pelo menos para os paises da
> américa latina :-/ ... tinha esquecido disso rsrsrs mercosul eu sei q é de
> boa .. o restante não sei como funciona .. depois vou abrir um issue sobre
> isso
> 
> @xmnlab https://github.com/xmnlab Acho que nenhum paíz da américa
> latina tem problemas para entrar no Brasil. Até onde eu sei, deixamos os
> participantes procurarem de visto e se for o caso eles entram em contato
> pedindo carta convite. Só precisa ter uma página com essa informação.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scipy-latinamerica/scipyla2016/issues/39.
> 
> ## 

Juan BC (from phone)

**Comment by xmnlab** [comment]
Thank you, Juan!

**Comment by JoaoFelipe** [comment]
Não sei se é preciso, mas usando o VisaHQ (https://www.visahq.in/citizens/) e olhando cada país da america latina, cheguei na seguinte lista: 

Cuba - precisa
El Salvador - precisa
Haiti - precisa
México - precisa
Nicarágua - precisa
República Dominicana - precisa

Argentina - não precisa
Bolivia - não precisa
Chile - não precisa
Colombia - não precisa
Costa Rica - não precisa
Equador - não precisa
Guatemala - não precisa
Honduras - não precisa
Panama - não precisa
Peru - não precisa
Uruguay - não precisa
Venezuela - não precisa

**Comment by rgaiacs** [comment]
@xmnlab vai pedir para algum dos embaixadores para escrever algo.

**Comment by ochoadavid** [comment]
Correção da lista anterior. As pessoas vindo do México não precisam:

> A partir del 16/05/2013, ciudadanos mexicanos portadores de pasaporte ordinario no necesitan de visa para entrar a Brasil cuando viajen con el propósito de desarrollar actividades de turismo, deportes, negocios, tratamiento médico, asistir a conferencias, eventos o ferias comerciales, en tránsito o cualquier otra actividad que no sea remunerada.

(http://cgmexico.itamaraty.gov.br/es-es/visas.xml)

**Comment by xmnlab** [comment]
@ochoadavid, muito obrigado pelas informações!

**Comment by xmnlab** [comment]
@olemis, podrías informarnos un enlace a una página oficial donde tiene informaciones sobre visa para cubanos ingresaren en Brasil?

**Comment by olemis** [comment]
@xmnlab ¿ algo como esto ... ?

http://havana.itamaraty.gov.br/es-es/tabla_de_precios_para_visas.xml
http://havana.itamaraty.gov.br/es-es/visas.xml

**Comment by rgaiacs** [comment]
@xmnlab Vai migrar a informação para o site durante a Páscoa.

**Comment by xmnlab** [comment]
@olemis gracias por los enlaces :)

**Comment by xmnlab** [comment]
pull request # 34. falta criar o submenu. foi adicionado dentro do menu participe.

**Comment by rgaiacs** [comment]
Vou fazer o menu. Desculpa a demora.

**Comment by rgaiacs** [comment]
Finalmente o menu apareceu. :-(

**Comment by xmnlab** [comment]
valeu!!
