### ISSUE TITLE
Review diversity

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#41]
https://github.com/scipy-latinamerica/website-scipyla2016/blob/master/scipyla2016/templates/about/diversity.html

@xmnlab Could you check if PyLadies Florianópolis is interested in running anything during SciPyLA?

**Comment by xmnlab** [comment]
I think we should use this guide of diversity:
https://github.com/yamila-moreno/pepa

It is really very interesting!! :)

**Comment by rgaiacs** [comment]
@xmnlab Could you take a executive decision here?

**Comment by xmnlab** [comment]
ok, I will write the diversity page using the pepa text!

**Comment by xmnlab** [comment]
done!
