### ISSUE TITLE
Auditoriums and multipurpose rooms reservation

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#42]
Auditoriums and multipurpose rooms reservation at UFSC.

**Comment by xmnlab** [comment]
As informações que você precisa podem ser esclarecidas com:
1- Secretaria de Cultura: Ramal 3850, para saber a disponibilidade do auditório da Reitoria ou outros espaços multiusos do Centro de Cultura e Eventos;
2- Secretaria dos Órgão Deliberativos: ramal 7302, para consultar a disponibilidade da Sala dos Conselhos.

**Comment by xmnlab** [comment]
auditório da Reitoria não disponível para a data do evento.

**Comment by xmnlab** [comment]
# Centros de Ensino da UFSC

Contatos para auditório e salas multiusos. O auditório deve estar disponível nos dias: 18, 19 e 20 de maio e as salas multiusos devem estar disponíveis no dia 16 e 17 de maio.

## ~~Centro de Ciências Agrárias (CCA)~~
- [x] Contato realizado.

Retorno: ESPAÇO NÃO DISPONÍVEL

http://cca.ufsc.br

**SECRETARIA**
- Ana Carla Bastos
  
  > Coordenadora de Apoio Administrativo
  > cca@contato.ufsc.br / 3721-5404
- Karina Karim da Costa Martins
  
  > Secretária Executiva
  > karina.martins@ufsc.br / 3721-5404

## Centro de Ciências Biológicas (CCB)
- [x] Contato realizado.

http://portal.ccb.ufsc.br/

Agenda e Reserva de Salas e Equipamentos do CCB

> http://portal.ccb.ufsc.br/salas-de-aula/

Salas de aula - ala antiga do CCB, próximo ao Colégio Aplicação:
- Sala CCB 508 (60 pessoas)
- Sala CCB 509 (100 pessoas)
- Sala CCB 511 (40pessoas)
- Sala CCB 512 (40 pessoas)
- Sala CCB 513 (30 pessoas)
- Sala CCB 517 (30 pessoas)
- Sala do Conselho (ver abaixo em Observações Gerais o item nº 5)
- Sala de Informática (EaD) – (15 pessoas) (necessidade de instalação de software, ver abaixo em Observações Gerais o item nº 6)

Salas de aula - ala nova CCB, Bloco A, no Córrego Grande:
- Sala MIP 002
- Sala MIP 003
- Sala MIP 006

## Centro de Comunicação e Expressão (CCE)
- [ ] Contato realizado.

http://www.cce.ufsc.br/

Reserva de Salas Para Eventos

> http://www.cce.ufsc.br/secao-de-apoio-a-eventos/
>  1° PASSO – Verificar na SAE – Seção de Apoio a Eventos (CCE Bloco B Sala 003) , se a data desejada está disponível. Essa informação também pode ser obtida pelo ramal  6326.
> 
> Secretaria de Apoio Administrativo
> +55 (48) 3721-9351 / cce@contato.ufsc.br

### Tarefas
- [x] contato para informação de contato direto da SAE – Seção de Apoio a Eventos;
- [] contato com a SAE;

## Centro de Ciências da Saúde (CCS)
- [x] Contato realizado.

### Retorno:
- ...

Agendador de espaço físico do CCS 

> http://reservas.ccs.ufsc.br/main/
- ~~Auditório Graduação (Capacidade: 120) ~~
- ~~Auditório Pós-graduação (Capacidade: 150)~~
- Laboratório de Informática (Capacidade: 35)
- Sala dos Conselhos (Capacidade: 30)
- Sala 922 - Multiuso (Capacidade: 40)
- Técnicas Alternativas (Capacidade: 12)

Coordenadora de Apoio Administrativo

> Serv. Tânia Regina Tavares Fernandes - 
> Email: tania.tavares@ufsc.br /  3721-9394 – 3721-9525 - 

## Centro de Ciências Jurídicas (CCJ)
- [ ] Contato realizado.

http://ccj.ufsc.br

Reservas:

> http://ccj.ufsc.br/reserva-salas/

Estrutura Física:
- 6 Salas de Multimídia – (computador com DVD, som ambiente e software para apresentações).
- 20 Salas de Aula – todas equipadas com aparelhos de ar-condicionado e com data-show.
- ~~1 Auditório com capacidade para 90 pessoas.~~
- 1 Biblioteca setorial com 15 mil exemplares.
- 1 Escritório Modelo de Assistência Jurídica que atende anualmente 5 mil pessoas.
- 1 Laboratório de Informática para os alunos da graduação e pós com 40 computadores.
- 2 Salas de Reunião.
- 20 Salas de Professores.

## Centro de Desportos (CDS)
- [ ] Contato realizado.

http://portalcds.ufsc.br/

## Centro de Ciências da Educação (CED)
- [ ] Contato realizado.

http://ced.ufsc.br/

Descrição das salas:
- http://reservas.ced.ufsc.br/index/instrucoes.php

Agenda do Auditório, Hall e Saguões:
http://reservas.ced.ufsc.br/Web/view-schedule.php?sid=1&sd=2016-5-16

Salas:
- Auditório (bloco A) - Capacidade: 100 pessoas;
- Sala de reuniões (bloco B) - Capacidade: 30 pessoas;
- Sala 109 e Sala 111 (bloco D) - Capacidade: 50 pessoas;
- Sala do Corpo (bloco A) - Capacidade: entre 10 e 20 pessoas;
- Hall do bloco A - Capacidade: 80 pessoas.;
- Saguão dos blocos C e D.

## Centro de Filosofia e Ciências Humanas (CFH)
- [x] Contato realizado.

Departamento de Filosofia
Universidade Federal de Santa Catarina
Florianópolis, SC, BRASIL
CEP: 88040-900

Telefone: +55 (48) 3721-4457
E-mail: wfil@cfh.ufsc.br

## Centro de Ciências Físicas e Matemáticas (CFM)
- [ ] Contato realizado.

Site:
- http://cfm.ufsc.br/

Contato não encontrado.

## Centro Socioeconômico (CSE)
- [ ] Contato realizado.

Site:
- http://cse.ufsc.br

Agenda Auditório:
- http://cse.ufsc.br/agenda-auditorio

Contatos

Coordenador de Apoio Administrativo: Roberto Carlos Alves
E-mail: cse@contato.ufsc.br
Fone +55(48) 3721-9585

## Centro Tecnológico (CTC)
- [ ] Contato realizado.

Campus Universitário Reitor João David Ferreira Lima
Rua Delfino Conti, s/n, Trindade
Florianópolis - Santa Catarina
CEP: 88040-900

Auditórios:
- http://portal.ctc.ufsc.br/files/2014/08/CTC31-INE-1%C2%B0-Pavto.-page-001.jpg
- http://portal.ctc.ufsc.br/files/2014/08/CTC06-Bloco-F-2%C2%B0-Pavto.-page-001.jpg
- http://portal.ctc.ufsc.br/files/2014/08/CTC39-40-43-Bloco-A-B-C-2%C2%B0-Pavto-page-001.jpg

Fone: 55 (48) 3721-9339 /9340 /9343 /9837
Fax: 55 (48) 3721-9770

**Comment by xmnlab** [comment]
- [x] Contato com o SENAI para salas multiusos

**Comment by xmnlab** [comment]
Pós-Graduação em Ciência da Computação – PPGCC (ppgcc.posgrad.ufsc.br) 
- [x] contato realizado

**Comment by xmnlab** [comment]
Auditórios para as palestras já reservados. 
As reservas para as salas dos tutoriais em andamento.

**Comment by rgaiacs** [comment]
@xmnlab Vai pedir a reserva das duas salas na biblioteca **hoje**.

**Comment by xmnlab** [comment]
reserva realizada.

Informações serão apresentadas, no fim do dia, em:

https://github.com/scipy-latinamerica/scipyla2016/blob/master/organization/reservations.md

**Comment by rgaiacs** [comment]
@xmnlab E as salas na biblioteca?

**Comment by xmnlab** [comment]
# Espaços reservados:

## Espaços da Biblioteca Universitária - BU

1.1      Auditório “Elke Hering” – com capacidade para até 80 pessoas, o auditório está equipado com poltronas dobráveis com pranchetas escamoteáveis confeccionadas em madeira, microcomputador com acesso à Internet, caixas de som, projetor multimídia (Datashow), DVD Player, microfone com e sem fio. Disponibilizado para a comunidade universitária nas segundas, terças, quartas e sextas-feiras das 7h30min às 22h e aos sábados das 8h às 17h. Nas quintas-feiras o auditório está reservado para uso exclusivo do Sistema de Bibliotecas Universitárias da UFSC (BU/UFSC). Espaço localizado no piso superior da Biblioteca Central.

1.2      Sala de projeção “Harry Laus” - com capacidade para até 40 pessoas, a sala está equipada com cadeiras estofadas com pranchetas, projetor multimídia (data-show), caixas de som, microcomputador com acesso à Internet, DVD Player, quadro branco e flipchart (folhas de papel não disponíveis). Disponibilizada de segunda a sexta-feira das 7h30min às 22h, e aos sábados das 8h às 17h. Espaço localizado no piso superior da Biblioteca Central.

1.3      Sala de projeção “Henrique da Silva Fontes” – com capacidade para até 24 pessoas, a sala está equipada com cadeiras estofadas com pranchetas, projetor multimídia (data-show), tela de projeção interativa, caixas de som, microcomputador com acesso à Internet, vídeo cassete, DVD Player, CD Player, televisão. Disponibilizada de segunda a sexta-feira das 7h30min às 22h, e aos sábados das 8h às 17h. Espaço localizado no piso superior da Biblioteca Central.

**Comment by rgaiacs** [comment]
@xmnlab Teria como você conseguir fotos dos espaços? Para colocarmos no site? @taliaga @braunmagrin
