### ISSUE TITLE
Translate https://github.com/scipy-latinamerica/website-scipyla2016 to Portuguese

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#44]
Need to translate https://github.com/scipy-latinamerica/website-scipyla2016/blob/master/scipyla2016/locale/pt/LC_MESSAGES/django.po.

Instructions are available at https://github.com/scipy-latinamerica/website-scipyla2016#translation.

**Comment by ocefpaf** [comment]
@xmnlab and @rgaiacs I can do this later today/tomorrow.  However, since I never did this before I might crash and burn and cry for help :stuck_out_tongue_winking_eye: Stay tuned...

**Comment by rgaiacs** [comment]
@ocefpaf Thanks. There a some software that can help you translate faster. For example there is https://github.com/vslavik/poedit/ (it is licensed under MIT/BSD) and http://www.emacswiki.org/emacs/PoMode (if you use Emacs :smiling_imp:  ). There is also some web applications, for example:
- http://pootle.translatehouse.org/
- https://www.transifex.com/
- https://localizejs.com/

Please use the one you prefer.

**Comment by xmnlab** [comment]
maybe transifex is a good tools for that :)

**Comment by xmnlab** [comment]
done.
