### ISSUE TITLE
Translate https://github.com/scipy-latinamerica/website-scipyla2016 to Spanish

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#45]
Need to translate https://github.com/scipy-latinamerica/website-scipyla2016/blob/master/scipyla2016/locale/es/LC_MESSAGES/django.po.

Instructions are available at https://github.com/scipy-latinamerica/website-scipyla2016#translation.

**Comment by leliel12** [comment]
Some translations are really weird i think all the diversity code must be in only one string (and also we can simple copy paste from the last year conference

**Comment by xmnlab** [comment]
where is the diversity text of the last year conference?

imho think we can use this text:
https://github.com/yamila-moreno/pepa

**Comment by taliaga** [comment]
Hi @leliel12 !
Let me know if you need any help with this, I am able to give a hand so that we can close the issue as soon as possible :)

**Comment by taliaga** [comment]
Ok, I've already started from the scratch with the spanish translations (from end to beginning just in case I get news of a WIP :p). Planning to finish them all before Carnival comes to an end.

**Comment by rgaiacs** [comment]
Muito antigo.
