### ISSUE TITLE
Add the scipyla into http://conference.scipy.org website

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#47]
Make contact to add scipyla into http://conference.scipy.org website

**Comment by xmnlab** [comment]
just waiting diversity page update ...

**Comment by xmnlab** [comment]
communication done by twitter

**Comment by rgaiacs** [comment]
I'm closing this based on https://github.com/scipy-conference/conference.scipy.org/pull/19.
