### ISSUE TITLE
Review forms used on website

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#48]
@knabben Could you check if the forms at the website are working as expected? Thanks very much in advance.

**Warning**: I made a few changes and you will need to update the packages and update the database.

**Comment by knabben** [comment]
- [x] Login
- [x] Sign up
- [x] Profile speaker / stuff submission
- [x] Review material

@rgaiacs do you have the ListView/templates for the submissions and voting on mind?

**Comment by knabben** [comment]
#12

**Comment by rgaiacs** [comment]
> do you have the ListView/templates for the submissions and voting on mind?

Not now.

@knabben Thanks for your review. :sparkling_heart:
