### ISSUE TITLE
Get estimation for print material

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#49]
@xmnlab I create https://github.com/scipy-latinamerica/scipyla2016/blob/master/budget/estimate.ods to store the estimation of the cost with print material. When you get the cost estimation from someone else please add to that spreadsheet.

**Comment by taliaga** [comment]
Hi @rgaiacs. I know the owners of a local printing store so I could help with the cost estimatives, and eventually take care of executing this task should the budget be approved. But I'd need more specific infos; particularly:
- What would a Bottom SciPyLA be?
- Size and sources of the stickers "adhesivos"?
- Is the cost of the "program" 0 because someone got it for free or is it actually unknown?

**Comment by rgaiacs** [comment]
> I know the owners of a local printing store so I could help with the cost estimatives, and eventually take care of executing this task should the budget be approved.

Thanks. It will be great.

> - What would a Bottom SciPyLA be?
> - Size and sources of the stickers "adhesivos"?

![img_20160115_115555](https://cloud.githubusercontent.com/assets/1506457/12354816/7dee8e60-bb7f-11e5-8a4f-478d0b4fa488.jpg)

This picture should help.

For the stickers we want the circle and badge one.

> Is the cost of the "program" 0 because someone got it for free or is it actually unknown?

The cost of the program isn't zero. Need to get a cost estimation for it.

**Comment by rgaiacs** [comment]
@taliaga Você pode me ligar na sexta-feira?

**Comment by rgaiacs** [comment]
@xmnlab Conversei com o @taliaga.
1. Vamos fazerer os adesivos e o programa. No programa deixaremos um espaço para anotações. Não teremos pasta, bolsa, caneta, lápis, ...
2. O programa será composto por duas folhas A3. Após o acabamento final ele será um livreto com 8 páginas de tamanho A4.
3. Vamos fazer os pedidos no início de Maio.

**Comment by xmnlab** [comment]
Ótimo :)

**Comment by taliaga** [comment]
Just for the records.

**Graficas**:
- http://plothouse.com.br/
- http://www.rdocomvisual.com.br/

**Crachás**:
- https://www.idealcards.com.br/#produtos
- http://www.identisul.com.br/contato/
- http://www.lineacracha.com.br/site/contato

**Comment by rgaiacs** [comment]
@taliaga Você poderia colocar a cotação na forma de tabela aqui?

**Comment by rgaiacs** [comment]
Desatualizado.
