### ISSUE TITLE
Define communication channel

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#50]
Could you add to https://github.com/scipy-latinamerica/scipyla2016/blob/master/README.md the communication channel that we will be using? We are using GitHub for store files plus issues and the mailing list to announcements. Soon we will have the website with some information and I hope that some newsletter before the event.

Should we use IRC? Google Hangouts chat group? ...

**Comment by xmnlab** [comment]
Ok!! :)

I think google hangouts chat group is fine :)

**Comment by xmnlab** [comment]
I think it is done.
