### ISSUE TITLE
Agenda (meeting) - 2016-01-13 - WiSE

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#52]
# Atividades do WiSE no SciPyLA 2016
- [ ] Tutoriais
- [ ] Palestras
# Obrigações do SciPyLA 2016
- [ ] Promoção dos parceiros (website e banner)
- [ ] Infraestrutura para tutoriais
- [ ] Infraestrutura para palestras
- [ ] Auxílio Financeiro Nacional
- [ ] Auxílio Financeiro Internancional
# Obrigações do WiSE
- [ ] Organização dos Tutoriais
- [ ] Organização das Palestras
- [ ] Criação de material promocional das atividades do WiSE
- [ ] Auxílio com textos para o site do SciPyLA 2016 (hotelaria, turismo, gastronomia, etc)
- [ ] Auxílio com a comunicação do SciPyLA 2016 (twitter, facebook, linkedin, newsletter, mailing list)
- [ ] Exploring the nightlife of Floripa in order to give a better conference 
# Composição do WiSE
- [ ] Anitas
- [ ] PyLadies Floripa
- [ ] PyLadies Fortaleza (**precisa serem contactadas**)
# Pré-eventos
- [ ] Março: PyTalks+DjangoGirls+SciPyLA
- [ ] Abril: SciPyLA Warm up (https://github.com/scipy-latinamerica/scipyla2016/issues/57)

**Comment by xmnlab** [comment]
### Atividades/Funções para o SciPyLA

* Produção de textos (hotelaria, turismo, gastronomia, etc);
* Designer;
* Comunicação (twitter, facebook, linkedin, newsletter, mailing list);
* Apoio na coordenação dos tutoriais;

### WiSE

* Definição de atividades
* Definição de grupo de trabalho
* Definição de recursos

**Comment by rgaiacs** [comment]
@xmnlab vamos editando o primeiro comentário para ficar "organizado". Normalmente isso é uma péssima prática mas esse é um dos casos onde vale a pena quebrar a regra.

**Comment by xmnlab** [comment]
:+1:

**Comment by rgaiacs** [comment]
@xmnlab Can we close this?

**Comment by xmnlab** [comment]
Seria legal deixar a ata aqui para fechar?

**Comment by rgaiacs** [comment]
> Seria legal deixar a ata aqui para fechar?

Sim.

**Comment by xmnlab** [comment]
# Ata - Atividades do WiSE no SciPyLA 2016

## Tutoriais
- A Melissa vai estar como responsável pelo WiSE SciPyLA.
- Pedir para o Raniere deixar a Melissa em contato com a Aleksandra para desenhar a estrutura da atividade.

## Palestras
- Ter uma ampla divulgação para receber trabalhos do maior número possível de palestras. Ter canal para apoio à mulheres para montar um projeto para submeter.

## Obrigações do SciPyLA 2016
- Promoção dos parceiros (website e banner);
  - parceiros: anitas, python brasil, pyladies, (mais algum grupo?)
- Infraestrutura para tutoriais
  - Ver sugestão com a Aleksandra
-  Infraestrutura para palestras
  - Ver sugestão com a Aleksandra
- Auxílio Financeiro Nacional
  - Temos intenção de prover o auxilio
- Auxílio Financeiro Internancional
  - Temos intenção de prover o auxilio

## Obrigações do WiSE
- Organização dos Tutoriais
  - Melissa junto com as anitas e pyladies estarão trabalhando nesse tema.
- Organização das Palestras
  - A principio o trabalho maior será de divulgação e apoio às mulheres interessadas para criar e submeter os trabalhos.
- Criação de material promocional das atividades do WiSE
  - A Julia tem uma indicação já :)
- Auxílio com textos para o site do SciPyLA 2016 (hotelaria, turismo, gastronomia, etc);
  - A Julia tem uma indicação já :)
- Auxílio com a comunicação do SciPyLA 2016 (twitter, facebook, linkedin, newsletter, mailing list);
  - A Melissa irá ajudar nesse item.
- Exploring the nightlife of Floripa in order to give a better conference
  - Todos podem ajudar postando no Twitter uma foto do lugar com uma breve descrição e marcando @ScipyLA :)

# Composição do WiSE
-  Anitas
- PyLadies Floripa
- PyLadies Fortaleza (precisa serem contactadas)
  - A Julia participa do grupo do whatsapp do pyladies brasil, ela pode dar uma força em fazer contato com os outros grupos pyladies

## Pré-eventos
- Março: PyTalks+DjangoGirls+SciPyLA
  - Assim que tivermos uma ideia sobre as atividades do WiSE, podemos ver algo específico para o pytalk. 
- Abril: SciPyLA Warm up (#57)
  - Assim que tivermos uma ideia sobre as atividades do WiSE, podemos ver algo específico para o SciPyLA Warm up.
