### ISSUE TITLE
Possible wording issue in the webpage

### ISSUE THREAD

**Issue by ocefpaf** [scipy-latinamerica/scipyla2016#53]
In https://github.com/scipy-latinamerica/website-scipyla2016/blob/master/scipyla2016/locale/es/LC_MESSAGES/django.po#L174

I guess that it should be `public than the` rather than `public that the talks.`

**Comment by xmnlab** [comment]
you're right! I will fix it.

**Comment by ocefpaf** [comment]
Can you please check https://github.com/scipy-latinamerica/website-scipyla2016/blob/master/scipyla2016/locale/pt/LC_MESSAGES/django.po#L79 as well?

Maybe it makes sense in the rendered page, but I am having a hard time translating the fragment `to your account and proceed to your`.

**Comment by ocefpaf** [comment]
In https://github.com/scipy-latinamerica/website-scipyla2016/blob/master/scipyla2016/locale/pt/LC_MESSAGES/django.po#L147

`Teen track` or `Track teen`?

E em português seria "Trilha Jovem?"  Ou deixamos em inglês mesmo?

**Comment by xmnlab** [comment]
this is the entire text: To submit a proposal, sign up or log in to your account and proceed to your account dashboard .

Deixei separado para não colocar as tags html dentro da marcação de tradução ...

**Comment by ocefpaf** [comment]
> Deixei separado para não colocar as tags html dentro da marcação de tradução ...

Ah o `poedit` tá quebrando isso.  Espero não fazer meleca com ele...  vamos ver.

**Comment by xmnlab** [comment]
O Raniere tinha sugerido a tradução de Jovem Cientista .. talvez colocar Trilha Jovem Cientista

**Comment by ocefpaf** [comment]
> talvez colocar Trilha Jovem Cientista

Gostei.  Pega carona no JC do CNPq sem ser cópia :wink:

**Comment by xmnlab** [comment]
alteração de texto em inglês no po feito!

**Comment by ocefpaf** [comment]
I guess that the line https://github.com/scipy-latinamerica/website-scipyla2016/blob/master/scipyla2016/locale/pt/LC_MESSAGES/django.po#L419 will be changed in the future.

**Comment by xmnlab** [comment]
o texto sobre diversidade não foi ajustado ..
minha sugestão é usar esse guia: https://github.com/yamila-moreno/pepa

E talvez envolver a Yamila no tema do WiSE :)

**Comment by ocefpaf** [comment]
OK @xmnlab.  Deixa eu acabar a tradução aqui e volto para isso.

**Comment by ocefpaf** [comment]
Closing this to avoid cluttering the issue tracker.
