### ISSUE TITLE
Promo sticker

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#54]
I added the SVG of SciPyLA inside a hexagram. We could made some stickers using it and send to people by mail if they agree to publish a photo of it somewhere on the web (blog, GNU Social, RedMatrix, Diaspora, Twitter, Facebook, Instagram, ...) and license it under CC-BY so that we can use it on our promotion material.

The total cost should be around R$100.00 (R$40.00 for 1m² of stickers + R$60.00 of mail fee).

@xmnlab Do you approve a future reimbursement for anyone that want to do this?

@xmnlab Do you know any designer that could get a better background color for the sticker?

**Comment by taliaga** [comment]
@rgaiacs do you have a link for this svg? I could get the background color modified. Also, this isn't considered in the estimate template mentioned in #49, right?

**Comment by rgaiacs** [comment]
> do you have a link for this svg?

I'm trying to keep all the SVG for stickers at https://github.com/scipy-latinamerica/scipyla2016/tree/master/stickers.

> Also, this isn't considered in the estimate template mentioned in #49, right?

"Stickers" in Portuguese is "adesivos". The template has a estimation for the SciPyLA stickers and a few others that attends could have interest in.

**Comment by taliaga** [comment]
thanks @rgaiacs and sorry for the late response. 
I'm asking for a budget of all these things right-away, I'll update the .ods as soon as I get the response. 
Final question:

> Do you know any designer that could get a better background color for the sticker?

 Which color would you like to change exactly? The green? Something in mind or do I\* have freedom of choice? (*the designer actually hehe)

**Comment by rgaiacs** [comment]
> I'm asking for a budget of all these things right-away, I'll update the .ods as soon as I get the response. 

Thanks.

> Which color would you like to change exactly?

The logo itself is OK. The background of https://github.com/scipy-latinamerica/scipyla2016/blob/master/stickers/hex-scipyla.svg, the light yellow.

> Something in mind

A better yellow.

**Comment by taliaga** [comment]
Got it, thanks!

**Comment by taliaga** [comment]
OK, I already have some news :). We should discuss more details about the t-shirts. I'll bring this issue in our next meeting.

**Comment by rgaiacs** [comment]
@taliaga Você pode me ligar nessa sexta-feira?

**Comment by rgaiacs** [comment]
Continuous mandou alguns adesivos. E estamos com problemas orçamentários.
