### ISSUE TITLE
create the scipyla ambassadors page

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#56]
Create a contact page about the scipyla ambassadors

**Comment by xmnlab** [comment]
done! just need to include the link into the menu.

**Comment by rgaiacs** [comment]
@xmnlab What is the address of the embassadors page? I couldn't find it.

**Comment by xmnlab** [comment]
The file path is
https://github.com/scipy-latinamerica/website-scipyla2016/blob/master/scipyla2016/templates/about/ambassadors.html

**Comment by xmnlab** [comment]
done!
