### ISSUE TITLE
Warm up SciPyLA

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#57]
# Warm-up SciPyLA

O Warm-up SciPyLA tem como objetivo reunir a equipe local e reunir os interessados da comunidade local para um dia de evento dentro do escopo do SciPyLA.
## Local:

CIASC (Capacidade: 58 pessoas)
## Data e horário:

16 de abril/2016, de 9h às 17h
## Atividades

O evento será realizado com a ajuda dos grupos PyLadies + WiSE, Python Floripa (grupo organizador do Python Brasil 2016) e Florianópolis Data Science.

As atividades serão apresentadas em breve (esperamos até dia 18).

**Comment by taliaga** [comment]
How about a webinar?

**Comment by xmnlab** [comment]
great idea. we could have 1 webinar every week.

one webinar from each country from latin america.

how do you think about that?

**Comment by leportella** [comment]
Thats bold! I like it1

Em sex, 5 de fev de 2016 às 01:26, Ivan notifications@github.com escreveu:

**Comment by xmnlab** [comment]
@gileno tivemos agora uma reunião com o @alexandrejaguar e o @rgaiacs e falamos em montar um plano para mini video aulas para fazer um esquenta do evento. Cubrir tópicos iniciais para preparar o grupo até o evento. @leportella, @melissawm  podemos fazer em parceria com o pyladies floripa.

o que acham?

**Comment by gileno** [comment]
@xmnlab gostei da ideia, os vídeos seriam motivacionais ou técnicos? Eu posso fazer algum no final de semana após o carnaval, mas antes é bom definir que tópicos serão comentados.

**Comment by xmnlab** [comment]
@gileno  acredito que serão mais videos técnicos.

abrimos uma issue específica para falar deste tema: https://github.com/scipy-latinamerica/scipyla2016/issues/75

Já começamos a escrever algumas ideia .. estamos centralizando tudo no primeiro comentário, pode edita-lo :)

se tiver problema com permissão me avise!

**Comment by xmnlab** [comment]
@leportella @melissawm @braunmagrin @sergiomario Conseguimos até sexta feira uma programação para esse evento? :)

**Comment by melissawm** [comment]
Pessoal,

Estou bem perdida na organização, e por isso não sei direito do que se
trata. O que precisa ser feito?

Abs

Melissa

Em dom, 13 de mar de 2016 às 23:55, Ivan notifications@github.com
escreveu:

**Comment by xmnlab** [comment]
Precisamos da programação do evento.

Temos definido que será duas horas para cada um dos tres grupos.

Seria bom ter a programação de cada grupo para divulgar e abrir para a
inscrição.

Conseguimos fechar essa programação até sexta agora?

@leportella, @melissawm, @braunmagrin, @sergiomario

**Comment by melissawm** [comment]
Só uma dúvida: quais são os três grupos?

Em seg, 21 de mar de 2016 às 23:23, Ivan notifications@github.com
escreveu:

**Comment by xmnlab** [comment]
Python Floripa, PyLadies/Wise, Florianopolis Data Science

:)

**Comment by leportella** [comment]
Vou ter que passar a organização... até fechar minha qualificação eu vou
ficar off

:/

Em seg, 21 de mar de 2016 às 23:34, Ivan notifications@github.com
escreveu:

**Comment by xmnlab** [comment]
@melissawm, @braunmagrin, @sergiomario, @rgaiacs, @taliaga

Como não recebi nenhuma programação, vamos definir hoje na reunião as
apresentações que serão feitas e, quem puder, pega uma apresentação para
fazer.

a ideia seria pegar temas de apoio à ciência, possivelmente usar os
materiais da software carpentry. Pensei em incluir LaTeX também na
programação e fazer na primeira hora do evento um PyInstall Fest.

atento aos comentários,
Ivan

**Comment by rgaiacs** [comment]
> a ideia seria pegar temas de apoio à ciência, possivelmente usar os
> materiais da software carpentry. Pensei em incluir LaTeX também na
> programação e fazer na primeira hora do evento um PyInstall Fest.

+1

**Comment by xmnlab** [comment]
@rgaiacs, segue minha proposta para o evento.

9h-10h - SciTools Install Fest
- Python (Anaconda)
- LaTeX
- Git

10h10-12h10 - Python (com base no material da software carpentry)

12h10-13h40 - Almoço (Região ruim para almoçar de sábado ... )

13h40-14h40 - LaTeX

14h50-15h50 - git/github  (com base no material da software carpentry)

16h00-17h00 - Open Science / Ciência Aberta (com base no artigo: The open research value proposition: How sharing can help researchers succeed).

@taliaga @melissawm @braunmagrin @sergiomario se vocês puderem pegar algum desses tutoriais vai ser muito legal :) 

Eu queria dar esse tutorial sobre Open Science :)

**Comment by xmnlab** [comment]
Gostaria de fechar esse item amanhã, para passar para o CIASC a programação e podermos abrir inscrições no dia 1.

**Comment by rgaiacs** [comment]
> 9h-10h - SciTools Install Fest

Acho que você vai precisar de mais tempo dependendo da conexão de internet.

> 10h10-12h10 - Python (com base no material da software carpentry)

Você poderia dar mais detalhes sobre quais partes do material você pretende cobrir?

> 12h10-13h40 - Almoço (Região ruim para almoçar de sábado ... )
> 
> 13h40-14h40 - LaTeX

Você poderia dar mais detalhes sobre o que você queria apresentar sobre LaTeX? Eu recomendo novatos a utilizarem http://sharelatex.com/ ou http://overleaf.com/ porque isso diminui significativamente os erros que eles podem ter e não vão entender o que significa.

> 14h50-15h50 - git/github (com base no material da software carpentry)

Novamente, o que você quer mostrar de Git e GitHub/GitLab? O materia da Software Carpentry demoro pelo menos umas 3h.

> 16h00-17h00 - Open Science / Ciência Aberta (com base no artigo: The open research value proposition: How sharing can help researchers succeed).

:-)

**Comment by xmnlab** [comment]
> Acho que você vai precisar de mais tempo dependendo da conexão de internet.

A ideia é ter uns pendrives e uns cds para não precisar ficar baixando ... senão realmente vai ficar impossível em 1 horas :)

> Você poderia dar mais detalhes sobre quais partes do material você pretende cobrir?

Eu só vou conseguir montar o conteúdo da atividade no próximo fim de semana :( mas a ideia é definir conforme o tempo disponível.

> Você poderia dar mais detalhes sobre o que você queria apresentar sobre LaTeX? Eu recomendo novatos a utilizarem http://sharelatex.com/ ou http://overleaf.com/ porque isso diminui significativamente os erros que eles podem ter e não vão entender o que significa.

Eu só vou conseguir montar o conteúdo da atividade no próximo fim de semana :( mas a ideia é definir conforme o tempo disponível. Quanto a questão de erros, acho bem válido o que você comentou ... se começar a pipocar erros lá será um problema ... Eu acho bem legal o sharetex/overleaf .. só me preocupo caso tiver algum problema de conectividade ... ainda mais que vai ser num fim de semana ... as vezes se tiver problema .. fica difícil conseguir alguém pra resolver o problema.

> Novamente, o que você quer mostrar de Git e GitHub/GitLab? O materia da Software Carpentry demoro pelo menos umas 3h.

Eu só vou conseguir montar o conteúdo da atividade no próximo fim de semana :( mas a ideia é definir conforme o tempo disponível.

Se alguém conseguir fazer essa gentileza de montar os conteúdos, ajudaria bastante. Senão eu faço no próximo fim de semana.

**Comment by rgaiacs** [comment]
> ```
> Acho que você vai precisar de mais tempo dependendo da conexão de
> internet.
> ```
> 
> A ideia é ter uns pendrives e uns cds para não precisar ficar baixando
> ... senão realmente vai ficar impossível em 1 horas :)

Não sei se você consegue instalar o Anaconda e o LaTeX direto do pendrive.

> ```
> Você poderia dar mais detalhes sobre quais partes do material você
> pretende cobrir?
> ```
> 
> Eu só vou conseguir montar o conteúdo da atividade no próximo fim de
> semana :( mas a ideia é definir conforme o tempo disponível.

Só toma cuidado com o tempo.

> ```
> Você poderia dar mais detalhes sobre o que você queria apresentar
> sobre LaTeX? Eu recomendo novatos a utilizarem
> http://sharelatex.com/ ou http://overleaf.com/ porque isso diminui
> significativamente os erros que eles podem ter e não vão entender
> o que significa.
> ```
> 
> Eu só vou conseguir montar o conteúdo da atividade no próximo fim de
> semana :( mas a ideia é definir conforme o tempo disponível. Quanto a
> questão de erros, acho bem válido o que você comentou ... se começar a
> pipocar erros lá será um problema ... Eu acho bem legal o
> sharetex/overleaf .. só me preocupo caso tiver algum problema de
> conectividade ... ainda mais que vai ser num fim de semana ... as
> vezes se tiver problema .. fica difícil conseguir alguém pra resolver
> o problema.

Se tiver problema de conexão você não vai conseguir instalar coisas que
dependem da internet e nem utilizar GitHub/GitLab.

> ```
> Novamente, o que você quer mostrar de Git e GitHub/GitLab? O
> materia da Software Carpentry demoro pelo menos umas 3h.
> ```
> 
> Eu só vou conseguir montar o conteúdo da atividade no próximo fim de
> semana :( mas a ideia é definir conforme o tempo disponível.
> 
> Se alguém conseguir fazer essa gentileza de montar os conteúdos,
> ajudaria bastante. Senão eu faço no próximo fim de semana.

**Comment by xmnlab** [comment]
> Não sei se você consegue instalar o Anaconda e o LaTeX direto do pendrive.

Anaconda eu sei que dá .. fizemos lá no pyladies .. o LaTeX eu preciso
fazer um teste.

> Só toma cuidado com o tempo.

:) sim

> Se tiver problema de conexão você não vai conseguir instalar coisas que
> dependem da internet e nem utilizar GitHub/GitLab.

A minha ideia inicial é não precisar da internet para instalar nada.
Quanto ao github, é verdade, mas ai no caso tento usar minha maquina como
servidor ...
mas espero realmente que nao tenha nenhum problema de conectividade.
Ainda nesse tema de conectividade, tenho que passar para o CIASC os sites
que vão ser acessados durante as palestras, assim eles já deixam
habilitados nas regras de segurança.

**Comment by melissawm** [comment]
Pessoal,

Vou conferir pq nunca fiz o teste, mas acredito que dá pra instalar o
texlive de pendrive sim. Só não sei no windows :) Realmente recomendo
overleaf e sharelatex nesses casos. Mas a minha apresentação não precisa
ser hands-on, posso só mostrar o que dá pra fazer e os interessados podem
seguir em casa com o material que eu forneço. O que vocês preferem?

Abs

Melissa

Em seg, 28 de mar de 2016 às 16:26, Ivan notifications@github.com
escreveu:

**Comment by xmnlab** [comment]
> Vou conferir pq nunca fiz o teste, mas acredito que dá pra instalar o
> texlive de pendrive sim. Só não sei no windows :) Realmente recomendo
> overleaf e sharelatex nesses casos.

:)

Mas a minha apresentação não precisa

> ser hands-on, posso só mostrar o que dá pra fazer e os interessados podem
> seguir em casa com o material que eu forneço. O que vocês preferem?

Acho que está bem, pois será apenas uma hora. Acho que seria pouco tempo
para a galera fazer algo durante a apresentação.

**Comment by xmnlab** [comment]
@melissawm @sergiomario @braunmagrin muito obrigado!!
evento realizado com sucesso! :)
