### ISSUE TITLE
Review of previus editions

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#59]
@damianavila and @fisadev Could you send us a very small review of the last edition of SciPyLA to go into the website? Thanks in advance.

**Comment by rgaiacs** [comment]
[Twitter](https://twitter.com/search?q=%40scipyla%20since%3A2015-05-01%20until%3A2015-05-31&src=typd) does help very much. =(

**Comment by damianavila** [comment]
I can write something but not before late next week... did you try pinging @leliel12? Maybe he have something already written, IIRC, he started a post-mortem some time ago on SciPyLA 2015

**Comment by rgaiacs** [comment]
I add a few tweets. Need to improve but I'm closing this issue for now.
