### ISSUE TITLE
Investigate the option to hold the event at UFSC

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#6]

**Comment by xmnlab** [comment]
O evento está sendo tramitado pela Oceanografia da UFSC, através do professor Fetter.

Já cadastramos o projeto na plataforma de projetos de extensão da UFSC (NOTES).

Estou esperando a confirmação da aprovação.

**Comment by rgaiacs** [comment]
@xmnlab A informação abaixo foi a que mandamos para a UFSC?

> O evento está previsto para acontecer nos dias 25, 26 e 27 de maio de 2016 e deverá acontecer de 9:30 a 13:00 e 14:30 a 19:30.
> 
> O pré-evento acontecerá nos dias 23 e 24 de maio de 2016 de 19:00 a 21:00. Dependendo da disponibilidade, as atividades poderão ser agendados em outros horários também.
> 
> O pós-evento acontecerá nos dias 28 e 29 de maio de 2016 de 9:00 a 17:00. Este horário dependerá das atividades que forem agendadas.

O evento ocorreria na semana anterior à PyCon, https://us.pycon.org/2016/events/, certo?

**Comment by xmnlab** [comment]
Exato.

Podemos trocar essa data. O importante é alterar a data apenas uma vez, para não ficar muito confuso.

**Comment by xmnlab** [comment]
evento já cadastrado como projeto de extensão na ufsc.
Aguardamos as declarações de isenção para subir o projeto dentro da fundação de extensão universitária para os trâmites financeiros.

**Comment by xmnlab** [comment]
já peguei os contatos para ver a disponibilidade de auditorios e salas multi-uso.

**Comment by rgaiacs** [comment]
I think that we can close this for now.
