### ISSUE TITLE
Error en links Sign up y Log in en tutoriales

### ISSUE THREAD

**Issue by jeudy** [scipy-latinamerica/scipyla2016#61]
Los links en la página de tutoriales no apuntan al URL correcto.

Deben ser: http://conf.scipyla.org/scipyla2016/account/signup/ y http://conf.scipyla.org/scipyla2016/account/login/

Actualmente están: https://conference.scipy.org/scipyla2016/account/signup/ y https://conference.scipy.org/scipyla2016/account/login/

Cambiar también la de "Account Dashboard"

**Comment by rgaiacs** [comment]
Close by https://github.com/scipy-latinamerica/website-scipyla2016/pull/15.
