### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#64]
Local:

![screen shot 2016-01-19 at 18 14 22](https://cloud.githubusercontent.com/assets/1506457/12430757/811ab7ec-bed8-11e5-9b64-f35bacc8fd10.png)

Online:

![screen shot 2016-01-19 at 18 14 16](https://cloud.githubusercontent.com/assets/1506457/12430760/8a3256be-bed8-11e5-993c-0196be00166a.png)

Shouldn't have the "Apply".

@knabben or @xmnlab Could you fix this?

**Comment by rgaiacs** [comment]
Fixed on production.

**Comment by rgaiacs** [comment]
The bug is back. =(

**Comment by xmnlab** [comment]
it seems ok now ...

**Comment by xmnlab** [comment]
I just type touch in wsgi file ...
