### ISSUE TITLE
Broken link - Submit Talk

### ISSUE THREAD

**Issue by arnaldorusso** [scipy-latinamerica/scipyla2016#65]
Hi there,

I found a bug while submiting a Talk.
`Internal Server Error`
I really did not found at [SciPyLa2016 github](https://github.com/scipy-latinamerica/website-scipyla2016/tree/master/scipyla2016)

Cheers

**Comment by rgaiacs** [comment]
@arnaldorusso The call for papers/talks starts only on March 1st. We will fix this "Internal Server Error" soon.

Could you provide more information about the link?

**Comment by arnaldorusso** [comment]
Sorry for anticipating this @rgaiacs :blush: 
I have just submited a tutorial and after that I'd submit a Talk
http://conf.scipyla.org/scipyla2016/proposals/submit/talk/

**Comment by rgaiacs** [comment]
@arnaldorusso no problem. Is great to have someone pushing the organization. =)
