### ISSUE TITLE
Typo on Facebook page

### ISSUE THREAD

**Issue by JoaoFelipe** [scipy-latinamerica/scipyla2016#66]
The facebook page (https://www.facebook.com/Scipy-Latin-America-1652863678298022/) has a typo:

"
SciPyLa is **thr** fourth conference about Scientific computing in Python in Latin America and will be held on 16 to 20 May 2016 in Florianópolis, Brazil.
"
It is also probably missing the subject ("it") before "will", but I'm not so sure if it is required.
Moreover, since it is talking about this year's conference, I would suggest specifying the year:

"
SciPyLa 2016 is the fourth conference about Scientific computing in Python in Latin America and it will be held on 16 to 20 May 2016 in Florianópolis, Brazil.
"

**Comment by leportella** [comment]
I corrected it! Thank you!
