### ISSUE TITLE
Create Media and Community Sponsors

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#68]
The Media and Community Sponsors page:

Argentina Python Communities:
- [ ] 

Brazilian Python Communities:
- [ ] GruPy-Al  - Grupo de usuários de Alagoas (links ...)
- [ ] GruPy-BA - Grupo de usuários da Bahia (links ...)
- [ ] GruPy-DF - Grupo de usuários do Distrito Federal (links ...)
- [ ] GruPy-ES - Grupo de usuários do Espírito Santo (links ...)
- [ ] GruPy-GO - Grupo de usuários de Goiás (links ...)
- [ ] GruPy-PB - Grupo de usuários da Paraíba (links ...)
- [ ] GruPy-PR - Grupo de usuários do Paraná (links ...)
- [ ] GruPy-RN - Grupo de usuários do Rio Grande do Norte (links ...)
- [ ] GruPy-RO - Grupo de usuários de Rondônia (links ...)
- [ ] GruPy-RP - Grupo de usuários de Ribeirão Preto (links ...)
- [ ] GruPy-RS - Grupo de usuários do Rio Grande do Sul (links ...)
- [ ] GruPy-SP - Grupo de usuários de São Paulo (links ...)
- [ ] Pug-Am - Grupo de usuários de Amazonas (links ...)
- [ ] Pug-CE - Grupo de usuários do Ceará (links ...)
- [ ] Pug-MA - Grupo de usuários do Maranhão (links ...)
- [ ] Pug-MG - Grupo de usuários de Minas Gerais (links ...)
- [ ] Pug-PE - Grupo de usuários de Pernambuco (links ...)
- [ ] Pug-PI - Grupo de usuários do Piauí (links ...)
- [ ] Pug-SC - Grupo de usuários de Santa Catarina (links ...)
- [ ] Pug-SE - Grupo de usuários de Sergipe (links ...)
- [ ] Python Floripa - Grupo de usuários de Florianópolis (links ...)
- [ ] PythonOnRio - Grupo de usuários do Rio de Janeiro (links ...)
- [x] PyLadies Floripa (links ...)
- [ ] Programando Ciência (http://programandociencia.com/)
- [ ] 

Venezuela Python Communities:
- [ ] ...  (links ...)

Bolivia Python Communities:
- [ ]  ...  (links ...)

Enterprises:
- [ ]  Anitas ...  (links ...)

Refs:
- http://pythonbrasil.github.io/wiki/comunidades-local

**Comment by rgaiacs** [comment]
> @rgaiacs, any suggestion ?

https://github.com/scipy-latinamerica/website-scipyla2016/pull/24

**Comment by xmnlab** [comment]
Thanks! :)

**Comment by xmnlab** [comment]
@leportella @melissawm vcs poderiam listar todos os grupos de pyladies do brasil para inserir na lista em Brazilian Python Communities?

E se conseguirem, poderiam colocar entre parenteses após o nome os links dos canais de comunicação do grupo (facebook, google, etc)

Talvez vocês poderiam entrar em contato com os grupos pyladies do brasil para inserir seus contatos nessa página: http://pythonbrasil.github.io/wiki/comunidades-local

Assim que a gente tiver a primeira versão da Media and Community Sponsors page ai vou ver de colocar o scipyla nessa página :)

**Comment by rgaiacs** [comment]
@xmnlab We can only advertise the groups that allow us.

**Comment by xmnlab** [comment]
yes .. the idea is all the Brazilian python groups have one page about all
Brazilian python groups :)

I think the original idea came from @erichideki.

**Comment by erichideki** [comment]
If you want, I can talk with the Pyladies and Django Girls about allowing put these logos. Do you want this?

**Comment by xmnlab** [comment]
can you do that? thank you very much :) it will be great :)

2016-02-07 21:28 GMT-02:00 Eric Hideki notifications@github.com:

**Comment by leportella** [comment]
Pyladies Brasil
http://twitter.com/pyladiesbrazil

Natal
https://www.facebook.com/PyLadiesNatal/

Recife
http://twitter.com/pyladiesrecife
https://www.facebook.com/pages/PyLadies-Recife/950001281692844

Fortaleza
https://twitter.com/PyLadiesFortal
https://www.facebook.com/PyLadiesFortaleza

Brasília
https://www.facebook.com/pages/pyladiesbsb

BH
https://www.facebook.com/pyladiesbh

RJ 
http://twitter.com/rio_pyladies
https://www.facebook.com/pyladiesrio

Duque de Caxias
https://www.facebook.com/pages/PyLadies-Duque-de-Caxias/

SP
https://twitter.com/PyLadiesSPaulo
https://www.facebook.com/PyLadiesSP

Campinas
https://www.facebook.com/PyLadiesCuritiba

Floripa
https://twitter.com/PyLadiesFloripa
https://www.facebook.com/PyLadies-Floripa-763762813730310/

**Comment by xmnlab** [comment]
Obrigado Letícia! Os dos outros países vou pedir para os embaixadores scipyla :)

**Comment by xmnlab** [comment]
@gileno poderias dar uma mão para construir essa página?

**Comment by xmnlab** [comment]
@jeudy @map0logo @govarguz uds podrían crear una lista de las comunidades relacionadas a python/python-científico/pyladies de sus países que puedan ayudarnos a retransmitir nuestros anuncios?

**Comment by gileno** [comment]
Posso @xmnlab, irei providenciar hoje.

**Comment by xmnlab** [comment]
Obrigado @gileno!

**Comment by gileno** [comment]
@xmnlab and @rgaiacs the Media and Community Sponsors page would be the same this [pull request](https://github.com/scipy-latinamerica/website-scipyla2016/pull/24)?

**Comment by rgaiacs** [comment]
> the Media and Community Sponsors page would be the same this pull request?

Media Sponsors are very special. We will handle case by case and their logo goes after the Bronze sponsors.

Friends have a very low entry barrier and the number of sponsors will be large so we will have a special pages for them.

We will have another special page for communities. Any group that advertise Python or any open source language used for scientific computing can request be on that list. Communities that help with the organization will be on the Friends page.

For example, @leportella is a member of PyLadies Florianópolis and is helping with the event. She can request that PyLadies Florianópolis be on the Friends list based on her contribution.

**Comment by braunmagrin** [comment]
Can I add new users groups/communities to the main comment or just create new comments in this issue?
I've just found https://twitter.com/pythonmexico.
