### ISSUE TITLE
Contact UFSC teachers to support the conference

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#7]

**Comment by rgaiacs** [comment]
@xmnlab Can we close this or we should keep it open to remember you.

**Comment by xmnlab** [comment]
I think we can close that

**Comment by lrsantos11** [comment]
Guys, I'm a UFSC Professor . You can use my name to support both inside and outside UFSC.

**Comment by xmnlab** [comment]
Great! Thank you Luiz-Rafael! Tomorrow I will check and include your name
in our files into repository!!
