### ISSUE TITLE
Accessibility access verification

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#70]
Accessibility access verification about auditorium, rooms, parks, etc.

**Comment by rgaiacs** [comment]
@xmnlab ou @braunmagrin  vai visitar os locais até 18 de Março.

**Comment by rgaiacs** [comment]
@xmnlab e @braunmagrin precisamos disso por escrito.

**Comment by xmnlab** [comment]
A biblioteca central dispõe de rampa de acesso para o piso superior. As salas tem acesso sem dificultadores. No auditório contamos com rampas de acesso lateral e poltronas, específicas para cadeirantes. 

No térreo contamos com um piso direcional até os banheiros.

**Comment by xmnlab** [comment]
Sobre o EFI: o local possui 2 elevadores, rampa para acesso e sanitários adaptados.

**Comment by xmnlab** [comment]
@rgaiacs vai colocar as informações no site amanhã (05/05).

**Comment by rgaiacs** [comment]
Feito.
