### ISSUE TITLE
Write content of program

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#76]
A few things to remember to have in the program:

![small-proc-1](https://cloud.githubusercontent.com/assets/1506457/12904171/80e49180-ceb4-11e5-95fc-f99038efd0e2.jpg)

![small-proc-2](https://cloud.githubusercontent.com/assets/1506457/12904183/952207fe-ceb4-11e5-9581-117de03e4505.jpg)

![small-proc-3](https://cloud.githubusercontent.com/assets/1506457/12904186/a02eee1e-ceb4-11e5-855a-f1814c552c7c.jpg)

**Comment by barbiemmc** [comment]
Hi! I saw you have the label "Desinger Needed" on this repo. Can I help with something? :) 
You can reach me by email (bmmunozcruzado@gmail.com), or twitter (@barbiemmc). Thanks!

**Comment by rgaiacs** [comment]
@barbiemmc Do you want to schedule a short meeting on Hangout/Skype/... or join our Gitter channel?

**Comment by xmnlab** [comment]
@rgaiacs has hablado con @barbiemmc ?

**Comment by rgaiacs** [comment]
Mandei email mas tive resposta.

**Comment by rgaiacs** [comment]
# Ideias para o layout

## Capa

![capa](https://cloud.githubusercontent.com/assets/1506457/14393970/b770e7bc-fdc1-11e5-9ab2-de3f4c1b3b30.png)

## Página

![pagina-impar](https://cloud.githubusercontent.com/assets/1506457/14393977/bfe0785e-fdc1-11e5-9ecf-65ecd1bb13e5.png)

Provavelmente com mais transparência.

**Comment by xmnlab** [comment]
+1

**Comment by melissawm** [comment]
Querem o esqueleto do programa em LaTeX? Aí só aguardo a opinião de um
designer pra fechar.

Em sex, 8 de abr de 2016 às 15:42, Ivan notifications@github.com escreveu:

**Comment by rgaiacs** [comment]
> Querem o esqueleto do programa em LaTeX?

@melissawm Por favor.

O documento principal é https://github.com/scipy-latinamerica/scipyla2016/blob/master/program/program.tex. Já coloquei a capa e a marca d'água.

**Comment by taliaga** [comment]
See comment on #95

**Comment by melissawm** [comment]
Great. I'll set this up today.

Em dom, 10 de abr de 2016 12:55, Tomas notifications@github.com escreveu:

**Comment by melissawm** [comment]
Quick question: is the program supposed to be in english?

Em dom, 10 de abr de 2016 às 13:09, Melissa Mendonça melissawm@gmail.com
escreveu:

**Comment by melissawm** [comment]
Also: can someone grant me access to the submission system so I can fetch
the abstracts for tutorials and talks to add to the program?

Thanks!

Melissa

Em dom, 10 de abr de 2016 às 17:17, Melissa Mendonça melissawm@gmail.com
escreveu:

**Comment by xmnlab** [comment]
Melissa, mexi aqui .. da uma olhada se já está OK!

**Comment by melissawm** [comment]
Funcionou, valeu.

Eu to terminando de adicionar as descrições completas e daqui a pouco mando
um pull request.

Abs

Em dom, 10 de abr de 2016 às 18:22, Ivan notifications@github.com
escreveu:

**Comment by xmnlab** [comment]
massa :)

muitíssimo obrigado :)

**Comment by rgaiacs** [comment]
@melissawm Obrigado pelo pull request. Nos provavelmente não vamos imprimir os resumos. Devido ao nosso budget super limitado.

**Comment by melissawm** [comment]
OK! Mais tarde termino uma primeira versão então. Seria interessante ter
uma versão eletrônica com os resumos e outra sem os resumos pra impressão?
Muita gente precisa ter o resumo publicado pra justificar viagem...

Não vou incluir ainda as palestras, pois temos que aguardar o final da
chamada de trabalhos. Vou depois conferir aqueles itens que vc mandou como
obrigatórios no programa.

Abs!

Melissa

Em seg, 11 de abr de 2016 14:42, Raniere Silva notifications@github.com
escreveu:

**Comment by rgaiacs** [comment]
> OK! Mais tarde termino uma primeira versão então.

Obrigado.

> Seria interessante ter uma versão eletrônica com os resumos e outra sem os resumos pra impressão?

Podemos ter sim.

> Muita gente precisa ter o resumo publicado pra justificar viagem...

:-)

Vamos incluir os resumos no site.

> Não vou incluir ainda as palestras, pois temos que aguardar o final da chamada de trabalhos. Vou depois conferir aqueles itens que vc mandou como obrigatórios no programa. 

OK.

**Comment by rgaiacs** [comment]
Parcialmente realizado.
