### ISSUE TITLE
Mother's room

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#77]
@xmnlab and @leportella Could you get a Mother's room for the event?

**Comment by melissawm** [comment]
@rgaiacs do you mean a breastfeeding room? Or is this something else?

**Comment by rgaiacs** [comment]
> @rgaiacs do you mean a breastfeeding room?

Yes.

**Comment by melissawm** [comment]
I can look into this.

Em seg, 8 de fev de 2016 23:01, Raniere Silva notifications@github.com
escreveu:

**Comment by rgaiacs** [comment]
@xmnlab ou @braunmagrin vão olhar isso até 18 de Março.

**Comment by xmnlab** [comment]
enviei email pro fetter. Assim que tiver resposta eu aviso!

**Comment by rgaiacs** [comment]
@xmnlab e @melissawm vamos ter essa sala?

**Comment by melissawm** [comment]
@rgaiacs lá no efi não costuma ter salas sobrando, é um prédio só de salas
de aula grandes. Eu poderia tentar em outro prédio mas acho que defeats the
purpose. Tentei pensar em alguma solução mas não consegui... Eu posso
oferecer minha sala caso seja necessário, mas é um pouco longe do efi.

Abs

Em sex, 22 de abr de 2016 às 14:43, Raniere Silva notifications@github.com
escreveu:

**Comment by rgaiacs** [comment]
@melissawm Obrigado. Vamos deixar para pensar nisso depois então.
