### ISSUE TITLE
Transfer logo from testing to production

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#79]
@xmnlab @leliel12 @knabben Do you know of one way to improve `dump.sh` so that it save the logos somewhere that we can send to the server?

**Comment by xmnlab** [comment]
No idea ... @gileno do you have some idea about that?

**Comment by gileno** [comment]
I never used but may work: https://github.com/leetrout/django-fixturemedia

**Comment by rgaiacs** [comment]
@xmnlab If anyone solve this problem today, February 17th, I will hard code the logos as a workaround.

**Comment by rgaiacs** [comment]
`fixtures/sponsor.json` has our sponsors but not their logos because the logo is a attribute of the benefit of each sponsor that is model as a one-to-many. **Need to export this one-to-many relationship to `fixtures/sponsor-benefits.json` and save the images at `scipyla2016/site_media/media/sponsor_files/`.

**Comment by rgaiacs** [comment]
Also be careful with database unique key!

**Comment by rgaiacs** [comment]
Out of date.
