### ISSUE TITLE
Contact teachers from other universities to support the conference

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#8]

**Comment by rgaiacs** [comment]
I will keep it open to remember me to contact CCSL.

**Comment by xmnlab** [comment]
@rgaiacs vc contactou o CCSL? :)

estamos fazendo contato com as universidades de LA através dos embaixadores. Acho que já podemos finalizar essa issue.

**Comment by rgaiacs** [comment]
> vc contactou o CCSL? :)

Ainda não. Faço isso na segunda.

**Comment by rgaiacs** [comment]
@xmnlab AInda não fiz o contato com o CCSL. :-(

Eu preciso fazer o contato com uma boa proposta. A maneira mais fácil do CCSL nos ajudar é com passagens de pessoas que passem pela USP. Para eles é factível passagens de Salvador -> São Paulo -> Floripa ou Floripa -> São Paulo -> Salvador mas passagens Salvador <-> São Paulo são mais difíceis.

**Comment by xmnlab** [comment]
Entendi, e qual é a proposta q vc tava pensando?

**Comment by rgaiacs** [comment]
> Entendi, e qual é a proposta q vc tava pensando?

Queria conseguir as minhas passagens através deles. Se mais alguém estivesse disponível para ajudar com um workshop de python posso incluí-lo no pedido e ver o que acontece.

**Comment by ocefpaf** [comment]
> Se mais alguém estivesse disponível para ajudar com um workshop de python

@rgaiacs estou afim the ajudar, mas a reunião anual da Regional Association que eu trabalho (nos EUA) será no meio da SciPyLA 2016! Estou negociando de não ir, já que a minha presença lá não é importante, mas meus empregadores fazem pressão... Aviso assim que tiver uma definição.
