### ISSUE TITLE
Options when submitting talks

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#84]
@xmnlab and @melissawm Could you review this ASAP?

![screen shot 2016-02-28 at 15 34 09](https://cloud.githubusercontent.com/assets/1506457/13380074/f6045d8e-de30-11e5-96d7-a1344f84a965.png)
# Submission type
- Talk or Poster
- Talk Only
- Poster Only
# Topic Track
- General
- Scientific Computing Education
- Geospatial Data in Science
# Domain symposium

None, only submit to tracks
Astronomy and Astrophysics
Bioinformatics
Geophysics
Vision, Visualization, and Imaging
Engineering
Computational Social Sciences and Digital Humanities

**Comment by xmnlab** [comment]
Só não entendi muito bem o topic tracks

**Comment by melissawm** [comment]
Sugestão: não pedir pra pessoa selecionar a trilha, e sim o domínio. Podemos montar as trilhas depois de escolhidas as palestras, de modo a organizar o programa. Acredito que entre os domínios precisamos ter uma categoria mais geral do tipo "Computação Científica ou Matemática Aplicada", não? (Eu por exemplo não saberia onde submeter um trabalho meu com as categorias listadas)

**Comment by xmnlab** [comment]
Também acho legal tirar a trilha. Seguindo as sugestões da @melissawm e adicionando mais uma, podemos incluir esses domínios já?
- Matemática Aplicada
- Computação Científica
- Data Science

**Comment by melissawm** [comment]
Proposta de categorias então:
- Scientific Computing Education
- Applied Mathematics/Scientific Computing
- Data Science
- Astronomy and Astrophysics
- Bioinformatics
- Geophysics
- Vision, Visualization, and Imaging
- Engineering
- Computational Social Sciences and Digital Humanities

**Comment by xmnlab** [comment]
Ok, vou adicionar isso no sistema daqui a pouco :)

**Comment by rgaiacs** [comment]
Corrigido em #84. Provavelmente responsável por #86.
