### ISSUE TITLE
change password doesn't work

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#85]
change password functionality doesn't work.

with EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
I can see the email information.

But if default backend doesn't work.

I add some variables about email on local_settings:

EMAIL_HOST
EMAIL_HOST_USER
EMAIL_HOST_PASSWORD
EMAIL_PORT
EMAIL_USE_TLS
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST

but it hasn't worked yet.

@rgaiacs @leliel12 @gileno @knabben, do you have some idea to fix this problem?

**Comment by rgaiacs** [comment]
> do you have some idea to fix this problem?

No.

**Comment by rgaiacs** [comment]
Se alguém conseguir tempo vamos tentar resolver.
