### ISSUE TITLE
Talks not listed for review

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#86]
Talks are not listed for review at http://conf.scipyla.org/scipyla2016/reviews/section/talks/all/ (need admin access to see that link).
# Steps to reproduce
1. Submit a talk.
2. Check that the talk is listed at submit.

![screen shot 2016-03-05 at 11 31 49](https://cloud.githubusercontent.com/assets/1506457/13547316/ff5a4ba2-e2c5-11e5-8612-ddfe644e20d2.png)
1. Check the list of all talks.

![screen shot 2016-03-05 at 11 32 13](https://cloud.githubusercontent.com/assets/1506457/13547318/07806ee2-e2c6-11e5-9e29-cc00a4533521.png)

**Comment by rgaiacs** [comment]
@xmnlab or @taliaga Could you fix this?

**Comment by xmnlab** [comment]
Não conseguirei ver antes de terça feira :(

**Comment by rgaiacs** [comment]
@braunmagrin Vai tentar resolver isso.

**Comment by taliaga** [comment]
Any update in this item?
I've logged in today and I can see some proposals listed there. Nevertheless, this issue makes me wonder whether we lost some or not :s

**Comment by xmnlab** [comment]
Acho que ainda está pendente ...

**Comment by rgaiacs** [comment]
@taliaga pelo que o @xmnlab falou o banco de dados está OK. Até agora tivemos apenas 2 palestras submetidas. Acho que as pessoas não submeteram porque não sabem se vão para floripa.

**Comment by rgaiacs** [comment]
@braunmagrin Você consegue trabalhar durante a páscoa para anunciarmos o auxílio financeiro? Isso deve ajudar as pessoas à submeterem as palestras.

**Comment by rgaiacs** [comment]
O @xmnlab falou que poderia ser permissão de usuário com base no grupo que ele pertence. Acabei de confirmar isso. Estou fechando por enquanto e depois corrigo para todo mundo.
