### ISSUE TITLE
Weekly meeting

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#88]
@xmnlab @leportella @taliaga @braunmagrin @melissawm Please fill http://whenisgood.net/scipyla2016. **We need to have some meeting to speed up the organization.**

**Comment by rgaiacs** [comment]
Date:   March 10, 2016
Time:   11:00:00 PM **UCT**

Brazil/East
Date:   March 10, 2016
Time:   8:00:00 PM

**Comment by ocefpaf** [comment]
Will that meeting be opened to outsiders?

**Comment by xmnlab** [comment]
acho que vamos fazer igual ao talk sobre software carpentry.
vamos criar um evento no hangout onair e divulgamos no twitter.
Confere, Raniere?

**Comment by rgaiacs** [comment]
> Will that meeting be opened to outsiders?

Yes. We are trying to run event as much open as we can. We will not record the meeting but we will keep notes on the issues.

**Comment by ocefpaf** [comment]
I'll try to participate.  I have a few questions on how to contribute and finding sponsors.

Thanks!

**Comment by rgaiacs** [comment]
Hangout: https://plus.google.com/events/ct0s2hibsod29u5mqkth34jrhf8

**Comment by rgaiacs** [comment]
E agendei alguns tweets.
