### ISSUE TITLE
Video recording

### ISSUE THREAD

**Issue by braunmagrin** [scipy-latinamerica/scipyla2016#89]
Look for prices of companies who record videos

**Comment by rgaiacs** [comment]
Tenho uma câmera, Preciso conseguir um cabo.

**Comment by rgaiacs** [comment]
Precisamos de um plano.

**Comment by xmnlab** [comment]
só das palestras ou dos tutoriais também?

só para as palestras ficam mais fácil pois é só um auditorio.
se for dos tutoriais já fica mais dificil conseguir isso, pois são 3 salas.

vou entrar em contato amanhã para ver o que consigo.

**Comment by rgaiacs** [comment]
> só das palestras ou dos tutoriais também?

Só das palestras.

> só para as palestras ficam mais fácil pois é só um auditorio.
>  se for dos tutoriais já fica mais dificil conseguir isso, pois são 3 salas.

É impossível gravar os tutoriais porque as salas são pequenas.

**Comment by xmnlab** [comment]
vamos gravar as palestras relampagos e os debates?

**Comment by xmnlab** [comment]
email enviado ao LED, responsável pelas gravações de eventos na UFSC.

**Comment by rgaiacs** [comment]
> vamos gravar as palestras relampagos e os debates?

Sim.

**Comment by xmnlab** [comment]
as palestras relampagos eu deixei no pedido para a LED

mas os debates e as aberturas e encerramentos eu tirei do pedido.

incluo?

**Comment by rgaiacs** [comment]
> mas os debates e as aberturas e encerramentos eu tirei do pedido.
> 
> incluo?

Sim.

**Comment by xmnlab** [comment]
ok, mando agora para eles

**Comment by xmnlab** [comment]
Ainda não tive retorno. Vou ligar amanhã para eles.

**Comment by xmnlab** [comment]
O LED, Laboratório de Educação a Distância, está verificando a disponibilidade. 

O Alexandre, coordenador do laboratório, comentou que estão com a equipe reduzida. Eu me ofereci em ajudar caso necessário.

**Comment by xmnlab** [comment]
@juliamachado possui tripé para câmera de gravação ela falou que pode emprestar, mas precisa verificar se este está completo.

**Comment by xmnlab** [comment]
estou ainda esperando retorno do Alexandre, vou ligar amanhã pra ele.

**Comment by xmnlab** [comment]
o setor está sem colaboradores devido a troca de reitoria da universidade e cancelamento de bolsas.

o @leliel12 sugeriu fazer streaming via twitch ou streaming por youtube.

Talvez daria pra fazer também por periscope (twitter).
