### ISSUE TITLE
Organize the track teen

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#9]
Maybe @argenpython and @EllaQuimica are interested?

**Comment by humitos** [comment]
@rgaiacs Hi! This my personal account and not @argenpython (that's only on Twitter :D)

Thank you for thinking on us for the Track Teen. We are very proud of that and we really like to be part again on the SciPyLA 2016 conference. Although, we see two problems with this and we are not sure how to handle them:
- Money: I did a "fast search" and I found that it's about USD 700 the flight from Lima, Perú to Florianópolis. I'm not really good at searching flight tickets so maybe we can find a good one but at least we have an estimation here. At the moment, there is no way for us to pay those tickets. Maybe we can find financial aid, but anyway, it's too much money for us.
- Language: We don't speak Portuguese. So, I think this is a limitation on what we can do. Besides, I can speak in English (I've never delivered a talk in English -so I can't promise it will be a good one :D) and @EllaQuimica doesn't speak English. Does the audience speak Spanish in that region? Because, maybe we can organize one talk in Spanish (our talk) and the rest in Portuguese from Brasilian people -as we did in Posadas, we counted with the participation of other speakers from other Argentinian cities.
- In-site contact: I also think we will need an in-site person to help us with some organization issues. It's another country, another language and I'm sure we will need to handle situation that we won't understand.

What do you think about this three initial points, @rgaiacs?

**Comment by rgaiacs** [comment]
> Thank you for thinking on us for the Track Teen. We are very proud of that and we really like to be part again on the SciPyLA 2016 conference. Although, we see two problems with this and we are not sure how to handle them:
> - Money: I did a "fast search" and I found that it's about USD 700 the flight from Lima, Perú to Florianópolis. I'm not really good at searching flight tickets so maybe we can find a good one but at least we have an estimation here. At the moment, there is no way for us to pay those tickets. Maybe we can find financial aid, but anyway, it's too much money for us.

We don't have any money for financial aid right now. We will let you know when we start to get sponsors.

> - Language: We don't speak Portuguese. So, I think this is a limitation on what we can do. Besides, I can speak in English (I've never delivered a talk in English -so I can't promise it will be a good one :D) and @EllaQuimica doesn't speak English. Does the audience speak Spanish in that region? Because, maybe we can organize one talk in Spanish (our talk) and the rest in Portuguese from Brasilian people -as we did in Posadas, we counted with the participation of other speakers from other Argentinian cities.

I think that the students could understand Spanish.

> - In-site contact: I also think we will need an in-site person to help us with some organization issues. It's another country, another language and I'm sure we will need to handle situation that we won't understand.

@xmnlab is your in-site person. I hope that we have more soon.

**Comment by xmnlab** [comment]
Hi @humitos I can help you all about the organization issues :)

Here, in Florianopolis, has a lot of international Latin American students so it will be very interesting :)

**Comment by rgaiacs** [comment]
@xmnlab and @leportella I want to invite [Larissa Garcia](http://g1.globo.com/tecnologia/campus-party/2016/noticia/2016/01/campus-party-aos-11-programadora-da-dicas-de-computacao-para-criancas.html) for the track teen. Larissa is the daughter of [Alexandre Oliva](http://www.fsfla.org/~lxoliva/). What do you think?

**Comment by leportella** [comment]
I don't know her but for me is ok! :D

**Comment by xmnlab** [comment]
+1

Maybe we can talk to @juliamachado about that. She has some project about
teens and tech and inovation.

Kanaan will organize the track teen, I think we need to call him to join in
this conversation.

I email him tomorrow.

**Comment by ankanaan** [comment]
I am in.  I can help with this, just need to get together with people and see what will do.  I have never participated in a meeting like this.  I know Julia Machado, has anybody talked to her yet?  I can do it if you like.

**Comment by rgaiacs** [comment]
Hi Kanaan,

> I am in.  I can help with this, just need to get together with people and see what will do.
> I have never participated in a meeting like this.

=)

> I know Julia Machado, has anybody talked to her yet?  I can do it if you like.

Julia Machado from Anitas, http://anitas.com.br/?
If yes, we already talked with her and she is going to collaborate with us.

**Comment by xmnlab** [comment]
@rgaiacs, do you talk to her about track teen too?

I know she is working with something called technovation challenge (maybe this website http://www.technovationchallenge.org)  ..  this is about teen girls and technology .. I don't know more details about that ... we need to ask to her .. 

@juliamachado you can talk to us more about technovation challenge?

**Comment by rgaiacs** [comment]
> @rgaiacs, do you talk to her about track teen too?

No.

**Comment by map0logo** [comment]
I have plenty of experience teaching Python to teens. I have in this moment
a group of several boys and girls under name "Club of Science" with weekly
meetings, developing video games, and planning Arduino projects

Regards!

**Comment by ankanaan** [comment]
hi Francisco, everybody,

this is very good to hear.  I guess first thing is to build a list of
people in the track teen and then we should get together and discuss the
possible activities.

I contacted Julia, we will talk today.

Who else is tracking teens?  (careful with the wording mr kanaan)

Antonio

**Comment by rgaiacs** [comment]
Esperando decisão do @ankanaan e da @juliamachado.

**Se formos ter a track teen precisa de um plano até 04 de Abril.**

**Comment by ankanaan** [comment]
Olás,

então tenho 3 dias?  Eu perdi essa mensagem do Raniere.  Ainda hoje
conversei com o William, um aluno de doutorado e trocamos umas ideias a
respeito.

Além de mim e do Francisco Palm tem alguém mais aqui dentro interessado?
Eu queria ter uma ideia melhor do que se espera do track-teen.

Francisco: onde estás ?  Oops, the only email I exchanged with Francisco
was in English.  Francisco, do you read Portuguese?  We should meet soon.
Physically or by telecon.

Tenho tentado conversar com a Júlia, mas nossas agendas andam muito
ortogonais.

abraços

Antonio

**Comment by xmnlab** [comment]
olá @ankanaan!

> então tenho 3 dias? Eu perdi essa mensagem do Raniere. Ainda hoje
> conversei com o William, um aluno de doutorado e trocamos umas ideias a
> respeito.

Se precisar de mais dias, nos avise quando poderás entregar a proposta e
nos organizamos :)

Só não esqueça que temos que ter tempo hábil para a divulgação :)

> Além de mim e do Francisco Palm tem alguém mais aqui dentro interessado?
> Eu queria ter uma ideia melhor do que se espera do track-teen.

Aquí está a chamada do track teen do ano passado e ao lado tem uma caixa
com o título "Evento finalizado", com um texto e fotos do evento realizado.

-> http://argentinaenpython.com.ar/track-teen-scipy-la-2015/

No próprio texto tem os contatos dos realizadores do ano passado, qualquer
coisa podem entrar em contato com eles para pegar umas dicas.

> Francisco: onde estás ? Oops, the only email I exchanged with Francisco
> was in English. Francisco, do you read Portuguese? We should meet soon.
> Physically or by telecon.

+1

> Tenho tentado conversar com a Júlia, mas nossas agendas andam muito
> ortogonais.

que pena :(

Um grande abraço!

**Comment by ankanaan** [comment]
já marquei com a Júlia, segunda de tarde.  Se tivermos mais interessados
poderíamos fazer um hangout.

abraços

Antonio

2016-04-01 18:36 GMT-03:00 Ivan notifications@github.com:

**Comment by xmnlab** [comment]
Legal!!

que horas vai ser?

**Comment by ankanaan** [comment]
Vou encontrá-la 14:30 queria falar um pouco com ela e depois podíamos
começar uma reunião com outros interessados.

Que tal abrir às 15:00?

**Comment by rgaiacs** [comment]
> Que tal abrir às 15:00?

+1 Adicionei na minha agenda.

**Comment by xmnlab** [comment]
@ankanaan vc passa o link do hangout?

**Comment by ankanaan** [comment]
blz, mando aqui na lista na hora

**Comment by ankanaan** [comment]
ois, começamos ?

https://talkgadget.google.com/hangouts/_/s76lmtlg4rb5xeet3idz7v4gbye?authuser=0&hl=en

**Comment by xmnlab** [comment]
Histórico das discussões:

@ankanaan:
olhem, conseguimos o lab de informatica do meu departamento.
na segunda é tranqulissimo.
pra nossa astro-atividade acho que podemos usar 2a 3a e 5a das 15h em diante.
que lhes parece?

@rgaiacs:
O que você acha de ter a aula da Larissa na 2ª e na terça ter a sua
atividade?

@ankanaan:
o que eu e a Júlia tínhamos falado era fazer a nossa atividade em três tardes, vocês acham muito?

@rgaiacs :
Eu tinha esquecido que vocês tinham pensado em dividir em três dias.
Mil desculpas. Sem problemas.
Você consegue encaixar a Larissa na programação?
Ou precisariamos de mais um slot para isso.

@juliamachado:
Olá pessoal! Boa noite!
Já conversei com a professora Giselle, da Escola Herondina, e provavelmente ela retorna até quarta-feira com a resposta de quantos alunos vão participar da atividade...
E falei sobre a atividade de 3 dias... ela achou um pouco extenso, mas também vai retornar com a resposta sobre isso.
Mais 2 coisas: além do lanche para os alunos, também vamos precisar de ônibus para o deslocamento.
Vou "investigar" um serviço da Prefeitura que consegue o ônibus para atividades escolares.
Caso eu não consiga o transporte com este meio, existe alguma verba para isso?
E mais um detalhe: acredito que o horário, das 15h às 17h30 (pois os alunos precisam retornar até às 18h) seja um pouco apertado?
Existe a possibilidade das atividades ocorrerem pela manhã??

@xmnlab:
Creio que o horário são vcs que definem. O que vocês definirem está ótimo.
Puxa, talvez vamos precisar correr atras de alguém para patrocinar o ônibus ou talvez a ufsc consiga emprestar o bus. Me avisa e eu peço pro Fetter verificar isso pra nós :)
Quanto ao lanche eu ainda nao consegui pensar em nada. Até agora só entrou um patrocínio ... Ainda estamos apertados :(

@rgaiacs: 
Lembrando que a Larissa está interessada em dar um aula de programação
para a garotada. Larissa é filha do Alexandre Oliva e participou do FISL
no ano passado. Seria muito bom ter a aula dela porque a idade dela é
mais próxima dos alunos que qualquer um de nós.

@ankanaan:
a Larissa seria uma outra atividade ou colocaríamos tudo na mesma coisa?
se 3 (dias) é demais, fazemos 2.
eu só acho difícil de fazer algo concreto em só duas aulas.  Mas a gente se adapta :-)
de manhã eu dou aula na 3a 4a e 5a 
se fizermos na segunda e na sexta tudo bem.
eu revisei os emails e acho que mandei o email do Lucas sem o attachment que tem os horários livres do lab, já mando outra vez por via das dúvidas.

[Horário Lab Informática 2016-1 - Plan1.pdf](https://github.com/scipy-latinamerica/scipyla2016/files/232287/Horario.Lab.Informatica.2016-1.-.Plan1.pdf)

oi Julia,
o que te parece 2a e 6a de manhã?
Ainda precisamos bolar um bom plano de atividade pra gurizada :-)

**Comment by rgaiacs** [comment]
A agenda precisa ser concluída na reunião do dia 25 com um plano de açao.

**Comment by ankanaan** [comment]
Eu posso fazer qq negócio mas preciso de retorno.

Minha proposta até agora foi diminuir a astro-atividade de 3 para 2 dias.
Mudar das tardes para as manhãs de 2a e 6a.

Eu ainda não entendi se a atividade da Larissa seria com as mesmas
crianças.  Se for como fazemos com o tempo?

O "plano de ação" é um programa do que eles vão fazer?

Antonio

2016-04-22 14:31 GMT-03:00 Raniere Silva notifications@github.com:

**Comment by rgaiacs** [comment]
> Minha proposta até agora foi diminuir a astro-atividade de 3 para 2 dias. Mudar das tardes para as manhãs de 2a e 6a.

OK. Você chegou a mandar uma descrição das atividades? Vou caçar no meu email mais tarde. Precisamos colocar a info no site.

> Eu ainda não entendi se a atividade da Larissa seria com as mesmas crianças.

Seria bom. Mas desde que você me consiga a reserva do laboratório podemos fazer com um outro grupo de crianças.

> O "plano de ação" é um programa do que eles vão fazer? 

Sim. E do que eu, @xmnlab, você e Julia ainda precisamos fazer. Temos apenas 3 semanas e nesse meio tempo eu tenho uma viagem para Nova York mais minha viagem para o Brasil de forma que só tenho duas semanas para fazer as coisas que faltam.

**Comment by map0logo** [comment]
Hi! excuse me that I haven't followed you recently.

I can read portuguese without problems.

I think that would be difficult to help to design the activity remotely,
proceed to plan and think about me as an assistant :-D

I can prepare a speech about some topic of science/game python programming
for kids, for example something about physics but depends on the other
activities planned. I will try with my perfect portuñol.

Cheers

F. Palm

2016-04-23 7:18 GMT-04:30 Raniere Silva notifications@github.com:

> Minha proposta até agora foi diminuir a astro-atividade de 3 para 2 dias.
> Mudar das tardes para as manhãs de 2a e 6a.
> 
> OK. Você chegou a mandar uma descrição das atividades? Vou caçar no meu
> email mais tarde. Precisamos colocar a info no site.
> 
> Eu ainda não entendi se a atividade da Larissa seria com as mesmas
> crianças.
> 
> Seria bom. Mas desde que você me consiga a reserva do laboratório podemos
> fazer com um outro grupo de crianças.
> 
> O "plano de ação" é um programa do que eles vão fazer?
> 
> Sim. E do que eu, @xmnlab https://github.com/xmnlab, você e Julia ainda
> precisamos fazer. Temos apenas 3 semanas e nesse meio tempo eu tenho uma
> viagem para Nova York mais minha viagem para o Brasil de forma que só tenho
> duas semanas para fazer as coisas que faltam.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/scipy-latinamerica/scipyla2016/issues/9#issuecomment-213726085

## 

---

fpalm@mapologo.org.ve
francisco.palm@gmail.com

cel: +58 +424 7228252
tel: +58 +274 6352001

---

Debemos ser libres, no para hacer lo que nos plazca, sino libres para
comprender muy profundamente nuestros propios instintos e impulsos. K

**Comment by ankanaan** [comment]
2016-04-23 8:48 GMT-03:00 Raniere Silva notifications@github.com:

> Minha proposta até agora foi diminuir a astro-atividade de 3 para 2 dias.
> Mudar das tardes para as manhãs de 2a e 6a.
> 
> OK. Você chegou a mandar uma descrição das atividades? Vou caçar no meu
> email mais tarde. Precisamos colocar a info no site.
> 
> Tinha feito um esboço, aqui vai outro esboço, com um pouco mais de detalhe.

Segunda-feira 9:00-10:15 Introdução ao python
                       10:45- 12:00 Introdução ao chimera
Sexta-feira       9:00-10:15 Uso do chimera para comunicar com instrumentos
virtuais (camera, telescopio, cupula).  Comando do telescópio.
                        10:45 - 12:00 Visita ao observatório e uso do
comando do telescópio como atividade prática.

> Eu ainda não entendi se a atividade da Larissa seria com as mesmas
> crianças.
> 
> Seria bom. Mas desde que você me consiga a reserva do laboratório podemos
> fazer com um outro grupo de crianças.

Em princípio o laboratório está liberado quando não tem aula de acordo com
a planilha que o Lucas me mandou e que repassei aqui na lista.  A gente só
precisa bater o martelo.

> O "plano de ação" é um programa do que eles vão fazer?
> 
> Sim. E do que eu, @xmnlab https://github.com/xmnlab, você e Julia ainda
> precisamos fazer. Temos apenas 3 semanas e nesse meio tempo eu tenho uma
> viagem para Nova York mais minha viagem para o Brasil de forma que só tenho
> duas semanas para fazer as coisas que faltam.

Aqui do meu lado eu preciso achar um jeito de deixar o chimera instalado
nos computadores do laboratório.

Eu e a Júlia, e espero, o William, precisamos desenhar com detalhe como
faremos as atividades com as criaturas

Antonio

**Comment by ankanaan** [comment]
esqueci de copiar a Júlia:

2016-04-23 8:48 GMT-03:00 Raniere Silva notifications@github.com:

**Comment by ankanaan** [comment]
oi Francisco,

lá que lês em português preguiçosamente respondo em português.

A gente certamente poderia usar tua ajuda na atividade com o chimera.

Se preferires podemos tentar marcar uma atividade extra, dentro dos
horários disponíveis no laboratório.

abraço,

Antonio

**Comment by xmnlab** [comment]
Assim que tivermos a confirmação da escola vou tentar fazer o pedido de transporte na ufsc: http://transportes.ufsc.br/

**Comment by ankanaan** [comment]
acabei de mandar email pra Giselle, professora da escola Herondina.  Mandei
cópia pro Ivan/Raniere/Julia.

abc

**Comment by map0logo** [comment]
2016-04-25 8:36 GMT-04:30 Antonio Kanaan notifications@github.com:

> oi Francisco,

Hola!

> lá que lês em português preguiçosamente respondo em português.

No problem, portuñol saves the day!

> A gente certamente poderia usar tua ajuda na atividade com o chimera.

Yeah chimera is very cool, but better if I can review the material before

Chimera es una aplicación muy extensa!!

> Se preferires podemos tentar marcar uma atividade extra, dentro dos
> horários disponíveis no laboratório.

También es posible, es para estudiantes de qué edad?
Se podría trabajar algo con mapas... some basics of geospatial analysis
with Python.

> abraço,
> 
> Antonio

Saludos

F. Palm

> On Sun, Apr 24, 2016 at 5:44 PM, Francisco Palm notifications@github.com
> wrote:
> 
> > Hi! excuse me that I haven't followed you recently.
> > 
> > I can read portuguese without problems.
> > 
> > I think that would be difficult to help to design the activity remotely,
> > proceed to plan and think about me as an assistant :-D
> > 
> > I can prepare a speech about some topic of science/game python
> > programming
> > for kids, for example something about physics but depends on the other
> > activities planned. I will try with my perfect portuñol.
> > 
> > Cheers
> > 
> > F. Palm
> > 
> > 2016-04-23 7:18 GMT-04:30 Raniere Silva notifications@github.com:
> > 
> > > Minha proposta até agora foi diminuir a astro-atividade de 3 para 2
> > > dias.
> > > Mudar das tardes para as manhãs de 2a e 6a.
> > > 
> > > OK. Você chegou a mandar uma descrição das atividades? Vou caçar no meu
> > > email mais tarde. Precisamos colocar a info no site.
> > > 
> > > Eu ainda não entendi se a atividade da Larissa seria com as mesmas
> > > crianças.
> > > 
> > > Seria bom. Mas desde que você me consiga a reserva do laboratório
> > > podemos
> > > fazer com um outro grupo de crianças.
> > > 
> > > O "plano de ação" é um programa do que eles vão fazer?
> > > 
> > > Sim. E do que eu, @xmnlab https://github.com/xmnlab, você e Julia
> > > ainda
> > > precisamos fazer. Temos apenas 3 semanas e nesse meio tempo eu tenho
> > > uma
> > > viagem para Nova York mais minha viagem para o Brasil de forma que só
> > > tenho
> > > duas semanas para fazer as coisas que faltam.
> > > 
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/scipy-latinamerica/scipyla2016/issues/9#issuecomment-213726085
> > 
> > 
> > ## 
> > 
> > ---
> > 
> > fpalm@mapologo.org.ve
> > francisco.palm@gmail.com
> > 
> > cel: +58 +424 7228252
> > tel: +58 +274 6352001
> > 
> > ---
> > 
> > Debemos ser libres, no para hacer lo que nos plazca, sino libres para
> > comprender muy profundamente nuestros propios instintos e impulsos. K
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/scipy-latinamerica/scipyla2016/issues/9#issuecomment-214032319
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/scipy-latinamerica/scipyla2016/issues/9#issuecomment-214309075

## 

---

fpalm@mapologo.org.ve
francisco.palm@gmail.com

cel: +58 +424 7228252
tel: +58 +274 6352001

---

Debemos ser libres, no para hacer lo que nos plazca, sino libres para
comprender muy profundamente nuestros propios instintos e impulsos. K

**Comment by xmnlab** [comment]
O Fetter vai revisar o modelo do pedido de autorização dos responsáveis dos alunos e em seguida a Giselle vai imprimir o arquivo e entregar às crianças.

É importante esse documento estar assinado já na sexta feira para dar sequência no tramite de pedido do ônibus.

**Comment by rgaiacs** [comment]
@xmnlab Voce vai colocar informações no site.
