### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#93]
Precisamos de uma forma de controlar os ingressos/assentos!

Gosto do http://eventbrite.com/ mas existem outras opções.

**Comment by leouieda** [comment]
Boa tarde, vocês tem alguma previsão de quanto será o preço da inscrição?

**Comment by rgaiacs** [comment]
> Boa tarde, vocês tem alguma previsão de quanto será o preço da inscrição?

Muito e muito provavelmentte não vamos cobrar pelas inscrições. Ainda estamos vendo como vamos fazer para diminuir a taxa de não comparecimento.

**Comment by leouieda** [comment]
@rgaiacs perfeito para ano de vacas magras!

**Comment by rgaiacs** [comment]
@xmnlab @taliaga Podemos utilizar o Eventbrite para controlar as inscrições e **compra de lembranças** como camisa, crachá, ...

**Comment by taliaga** [comment]
Looks very promising! +1 for Eventbrite

**Comment by xmnlab** [comment]
parece bacana :)
+1

**Comment by rgaiacs** [comment]
Screenshots of workflow:

![screen shot 2016-03-22 at 12 58 50](https://cloud.githubusercontent.com/assets/1506457/13952368/0a047d14-f02e-11e5-9d59-1d0fffc658aa.png)

![screen shot 2016-03-22 at 12 59 17](https://cloud.githubusercontent.com/assets/1506457/13952392/0f4d942c-f02e-11e5-97b6-08200672b083.png)

![screen shot 2016-03-22 at 12 59 42](https://cloud.githubusercontent.com/assets/1506457/13952398/134fcbd0-f02e-11e5-9367-d27f952cea3e.png)

![screen shot 2016-03-22 at 13 00 02](https://cloud.githubusercontent.com/assets/1506457/13952408/17fee4c2-f02e-11e5-98f3-d65cb26c965c.png)

@xmnlab Acho que poderíamos abrir ingressos antecipados para quem quiser crachá ou camisa ou alguma outra coisa.

**Comment by xmnlab** [comment]
Que massa!

Acho que seria bom, atë mesmo pra galera ja ir comprando as passagens

**Comment by rgaiacs** [comment]
O Eventbrite tem uma categoria especial para items adicionais.

![screen shot 2016-03-27 at 02 08 32](https://cloud.githubusercontent.com/assets/1506457/14063253/3a75c75a-f3c1-11e5-8390-b868299f68fb.png)

![screen shot 2016-03-27 at 02 09 34](https://cloud.githubusercontent.com/assets/1506457/14063254/3f45b86c-f3c1-11e5-86a4-97a6343a964d.png)

Pretendo abrir o primeiro lote de ingressos com duas opções: Ingresso gratuito e Ingresso com doação. Ingresso gratuito é apenas o ingresso. Ingresso com doação libera os itens adicionais (é possível fazer doação de R$1,00).

**Comment by rgaiacs** [comment]
@xmnlab R$20,00 por crachá + programa e R$30,00 por camisa?

Quero uma resposta hoje.

cc @taliaga @braunmagrin @jeudy @melissawm

**Comment by rgaiacs** [comment]
![screen shot 2016-03-28 at 12 42 28](https://cloud.githubusercontent.com/assets/1506457/14077389/e2b8d21e-f4e2-11e5-96ee-21f0711f6516.png)

![screen shot 2016-03-28 at 12 42 16](https://cloud.githubusercontent.com/assets/1506457/14077391/e6f998e0-f4e2-11e5-96e3-4804e4646c41.png)

**Comment by xmnlab** [comment]
+1 para: opção entrada gratuita + entrada com doação; valores crachá e camiseta e; arte da camiseta (talvez ba frente eu deixaria no lado esquerdo bem pequeno o texto SciPy Latin America) 

;)

**Comment by taliaga** [comment]
Tenho novidades sobre camisetas, parcero meu que trabalha com camisetas se ofereceu a patrocinar as camisetas do scipy dando um desconto importante. Podemos conversar?

**Comment by xmnlab** [comment]
Ótima notícia :)

**Comment by rgaiacs** [comment]
Live: https://www.eventbrite.com/e/bilhetes-scipy-latin-america-2016-23050125546

**Comment by rgaiacs** [comment]
O primeiro lote de ingressos está esgotado. Mais ingressos depois que tivermos o programa.
