### ISSUE TITLE
Informações a serem requisitadas à FAPEU

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#94]
@xmnlab e @braunmagrin precisamos das seguintes informações:
1. Procedimentos para compras de passagens aéreas nacionais e internacionais pela FAPEU.
2. Procedimentos para reserva de hotel pela FAPEU.
3. Procedimentos para reserva de Airbnb pela FAPEU.
4. Procedimentos para pagamento de diárias pela FAPEU.
5. Procedimentos para reserva de jantar pela FAPEU.
6. Procedimentos para pagamento da gráfica pela FAPEU.
7. Procedimentos para reembolse pela FAPEU. Por exemplo para taxi.

**Todos os procedimentos devem ser o mais detalhado possível e devem incluir**
- Fluxograma do procedimento (incluindo assinaturas).
- Prazos de cada passo no fluxograma.
- Telefone de contato da pessoa que cuida disso.
- Se for necessário um formulário, devemos ter link para o formulário e um exemplo fictício preenchido.

**Comment by xmnlab** [comment]
email enviado para FAPEU
