### ISSUE TITLE
Folheto / Afiche  A4

### ISSUE THREAD

**Issue by xmnlab** [scipy-latinamerica/scipyla2016#95]
Criação de folheto A4 para divulgação do evento.

Pode ser utilizado como base o arquivo:

https://github.com/scipy-latinamerica/scipyla2016/blob/master/brochure/template.tex

Deve ter versão em português e espanhol.

**Comment by xmnlab** [comment]
@jeudy nos puede echar una mano con esa actividad? :)

**Comment by melissawm** [comment]
Ivan,
Vc tem o arquivo vetorial original? Aí eu posso acrescentar as infos e
gerar o poster.

Abs

Melissa

Em dom, 27 de mar de 2016 às 22:32, Ivan notifications@github.com
escreveu:

**Comment by rgaiacs** [comment]
> Vc tem o arquivo vetorial original?

Usa como ponto de partida: https://github.com/scipy-latinamerica/scipyla2016/blob/master/program/capa.svg.

**Comment by taliaga** [comment]
Caros,
Nao se preocupem com o layout gráfico dos materiais. Podem focar no conteudo mesmo, depois eu alinho com a designer pra ter uma mesma cara tanto do Banner (de lona) do Crachá, o folheto A4 e o programa.
 @melissawm @rgaiacs @xmnlab

**Comment by xmnlab** [comment]
:)

Obrigado Tomas!!

**Comment by rgaiacs** [comment]
Substituido por outros issues.
